// Canonical OLL formula catalog cloned from Acubemy (setup + algorithms).
// Trainer and tests import this module directly.
export const ollCases = [
  {
    "id": "OLL -1",
    "category": "Dot Case",
    "preview": "../../previews/oll-1.svg",
    "setup": "F R′ F′ R U2 F R′ F′ R2 U2 R′",
    "solutions": [
      "R U2 R′ R′ F R F′ U2 R′ F R F′",
      "F R U R′ U′ S F′ R U R′ U′ R′ F R f′",
      "y F R U R′ U′ F′ r′ U r2 U′ r2 U′ r2 U r′",
      "y R U′ R2 D′ r U′ r′ D R2 U R′",
      "y′ R U′ R2 D′ r U′ r′ D R2 U R′",
      "F R U R′ U′ F′ U2 F U R U′ R′ F′ r U R′ U′ r′ F R F′",
      "R U B′ R B R2 U′ R′ F R F′",
      "f R U R′ U′ R f′ U′ r′ U′ R U M′",
      "L′ U2 L2 F′ L′ F U2 L F′ L′ F",
      "M R U R′ U R U′ R′ U r U2 r′ U′ M′",
      "y R′ U R2 D r′ U r D′ R2 U′ R",
      "y L′ U L2 D l′ U l D′ L2 U′ L",
      "R U2 R2 F R F′ U2 R′ F R F′",
      "R′ U′ F R′ F′ R2 U R f′ U′ f",
      "r U R′ U R′ r2 U′ R′ U R′ r2 U2 r′",
      "U′ R U′ R2 D′ r U′ r′ D R2 U R′",
      "R U R′ S R′ U′ R U R S′ U F R′ F′ R",
      "R U2 R′ l′ U l F′ U2 R′ F R F′",
      "U F R′ F′ R U S′ R U′ R′ y′ r U′ r′ F R′ F′ r",
      "U R U R′ U R′ F R F′ U2 y′ r′ U′ R U M′",
      "F R′ F′ R U2 R U′ R′ y′ r′ U r U′ r′ U′ r",
      "y F U R′ F R F2 U′ y′ R′ F R F′",
      "y F U R′ F R F2 U′ F′ L F L′",
      "R U B′ l U l2 x′ U′ R′ F R F′"
    ]
  },
  {
    "id": "OLL -2",
    "category": "Dot Case",
    "preview": "../../previews/oll-2.svg",
    "setup": "f U R U′ R′ f′ F U R U′ R′ F′",
    "solutions": [
      "F R U R′ U′ F′ f R U R′ U′ f′",
      "y′ R U′ R2 D′ r U r′ D R2 U R′",
      "y r U r′ U2 R U2 R′ U2 r U′ r′",
      "F R U R′ U′ F′ U2 F U R U′ R′ F′",
      "y2 F′ L′ U′ L U S′ L′ U′ L U f",
      "y r U r′ U2 r U2 R′ U2 R U′ r′",
      "R′ U2 r U′ r′ U2 r U r′ U2 R",
      "y l′ U′ l U2 L′ U2 L U2 R′ F R",
      "r′ U′ r R′ U′ R U′ R′ U R U2 r′ U r",
      "y r U R′ U2 R U2 r′ U2 r U′ r′",
      "y2 F R′ F′ R U2 F R′ F′ R2 U2 R′",
      "y R′ U R2 D r′ U′ r D′ R2 U′ R",
      "y′ R′ F R F′ U2 R′ F R F2 U2 F",
      "F R′ F′ U2 r U R′ U R2 U2 r′",
      "F R U r′ U′ R U R′ M′ U′ F′",
      "R U2 R2 F R F′ U2 R′ F R F′ U2 F R′ F′ r U R U′ r′",
      "F R U R′ U′ S R U R′ U′ f′",
      "y2 f U R U′ R′ S′ U R U′ R′ F′",
      "y L F L′ U2 R U2 R′ U2 L F′ L′",
      "y′ r′ U′ R U2 R′ U2 r U2 r′ U r",
      "R′ F′ U′ f U′ R U R′ S′ U R",
      "U r U r′ U2 r U2 R′ U2 R U′ r′",
      "y′ L′ U R L U2 R′ U L F′ L′ F U R′ F R F′",
      "y R′ F′ R U2 r′ F2 r U2 R′ F R",
      "y2 F R′ F′ R2 U R′ F′ U2 F U′ R U′ R′",
      "y2 R U R′ U F′ U2 F R U′ R2 F R F′",
      "M′ U′ r′ F R U F U′ R U R′ U′ F′",
      "y l′ U′ l U2 L′ U2 L U2 l′ U l",
      "y R′ F′ R U2 L′ U2 L U2 R′ F R",
      "U L F L′ U2 R U2 R′ U2 r U′ r′",
      "y R′ F′ r U2 r′ F2 R U2 R′ F R",
      "y′ F R U′ R′ F R U′ R′ F′ L′ U L F′ L′ U L",
      "y R′ F′ r U2 L′ U2 l U2 R′ F R",
      "y′ L′ U L2 D l′ U′ l D′ L2 U′ L",
      "U′ R U′ R2 D′ r U r′ D R2 U R′",
      "U′ R2 F R F′ U′ R U′ R2 F R F′ U R",
      "U′ F R′ F′ R U′ F′ U′ r U2 R′ U r′ F2 R",
      "U′ R U R′ S U′ R′ U S′ U R′ U F′ U F R",
      "U2 F R′ F′ R U2 F R′ F′ R2 U2 R′",
      "U2 R U S R′ U R U′ F R′ f′ R′",
      "U F R′ F′ R U2 R U′ R′ F′ r′ F2 r U F",
      "U R U R′ U′ R f R f′ U R′ F′ U′ r U′ r′ F2",
      "F R′ F′ R U R U′ f R f′ U R′ U′ R U′ R′",
      "R U R′ U2 F′ U′ L′ U L U F U′ R U2 R′",
      "y′ r′ U′ r U2 R′ U2 R U2 r′ U r",
      "y′ R′ F R F′ U2 R′ F R y′ R2 U2 R",
      "r′ D R2 U R′ U2 R U′ R2 D′ r"
    ]
  },
  {
    "id": "OLL -3",
    "category": "Dot Case",
    "preview": "../../previews/oll-3.svg",
    "setup": "F U R U′ R′ F′ U f U R U′ R′ f′ y",
    "solutions": [
      "y′ f R U R′ U′ f′ U′ F R U R′ U′ F′",
      "y′ F R U R′ U′ F′ U f′ L′ U′ L U f",
      "r′ R2 U R′ U r U2 r′ U M′",
      "y F U R U′ R′ F′ U F R U R′ U′ F′",
      "y F R U R′ U′ R U R′ U′ F′ U′ F R U R′ U′ F′",
      "y′ f R U R′ U′ f′ R′ F′ U′ F U R",
      "y R′ F2 R2 U2 R′ F R U2 R2 F2 R",
      "y f′ L′ U′ L U f U F R U R′ U′ F′",
      "y′ F R U R′ U′ F′ U2 R′ U′ F′ U F R",
      "y′ F′ U′ L′ U L F L F U F′ U′ L′",
      "y f′ L′ U′ L U f U′ F′ L′ U′ L U F",
      "f U R U′ R′ S′ R U′ R′ U′ R U R′ F′",
      "y2 L F U F′ U′ F U F′ U′ L′ y′ L F U F′ U′ L′",
      "r U R′ U R U2 r′ U r U R′ U′ r′ R U R U′ R′",
      "f U R U′ R′ S′ R′ F′ R U R U′ R′",
      "y′ F R′ F′ R U R U′ R′ U′ R U R′ U′ R′ F R F′",
      "y2 M′ U r′ U2 r U R′ U R2 r′",
      "L′ U′ L U L F′ L′ S′ L′ U′ L U f",
      "y′ x′ R U2 R2 F2 R U R′ F2 R2 U2 R′ x",
      "M R U R′ U r U2 r′ U M′",
      "F U2 F R′ F′ R U R U R′ U F′",
      "y2 R′ U F′ U F U F R′ F′ R U2 R",
      "M U l′ U2 l U L′ U L M′",
      "L′ l U l′ U2 l U L′ U L M′",
      "R r′ U R′ F2 R U r′ F r2 R′",
      "R f′ U′ f U R D r′ U′ r D′ R′",
      "r′ R U R′ F2 R U L′ U L M′",
      "y2 l′ L2 U L′ U l U2 l′ U M",
      "F R′ F′ R U′ S U′ R U R′ S′ R U R′",
      "U′ f R U R′ U′ f′ U′ F R U R′ U′ F′",
      "r′ R2 U R′ U r U2 r′ U r R′",
      "L′ l U R′ F2 R U L′ U L r R′",
      "L′ R2 B R′ B L U2 L′ B M′ x′",
      "r′ R2 U R′ U r U2 r′ U R′ r",
      "y2 R′ U′ F′ U F R F R U R′ U′ F′",
      "y L U2 L F′ L′ F U F U F′ U L′",
      "y′ S U R U R2 U′ R2 U R U S′",
      "y L F2 L2 U2 L F L′ U2 L2 F2 L′"
    ]
  },
  {
    "id": "OLL -4",
    "category": "Dot Case",
    "preview": "../../previews/oll-4.svg",
    "setup": "F U R U′ R′ F′ U′ f U R U′ R′ f′ y",
    "solutions": [
      "y′ f R U R′ U′ f′ U F R U R′ U′ F′",
      "y′ f R U R′ d′ l′ F R U R′ U′ F′",
      "y F U R U′ R′ F′ U′ F R U R′ U′ F′",
      "M U′ r U2 r′ U′ R U′ R′ M′",
      "y f′ L′ U′ L U f U′ F R U R′ U′ F′",
      "y′ R′ F2 R2 U2 R′ F′ R U2 R2 F2 R",
      "l L2 U′ L U′ l′ U2 l U′ M′",
      "y f′ L′ U′ L U f U F′ L′ U′ L U F",
      "y F′ L′ U′ L U F U′ f R U R′ U′ f′",
      "R U R′ U′ R′ F R S R U R′ U′ f′",
      "y2 L F U F′ U′ F U F′ U′ L′ F R U R′ U′ F′",
      "y F U R U′ R′ F′ U F′ L′ U′ L U F",
      "y F U R U′ R′ F′ R′ F′ U′ F U R",
      "R′ F R F′ U′ S R′ U′ R U R S′",
      "R′ F′ U′ F U R f R U R′ U′ f′",
      "y′ F′ U′ L′ U L F U F R U R′ U′ F′",
      "F′ U2 F′ L F L′ U′ L′ U′ L U′ F",
      "l′ U′ L U′ L′ U2 l2 U L′ U′ M′ U L U′ L′",
      "y2 M′ R′ U′ R U′ r′ U2 r U′ M",
      "R r2 F′ r U′ R′ F2 R U′ M′",
      "y x′ R U2 R2 F2 R U′ R′ F2 R2 U2 R′ x",
      "y F U′ R U′ R′ U′ R′ F R F′ U2 F′",
      "y′ F R U′ R′ U R U R′ F′ f R U R′ U′ f′",
      "R r′ U′ r U2 r′ U′ M′ r′ R2 U′ R′ M′",
      "r′ R U′ r U2 r′ U′ R U′ R′ M′",
      "r′ R U′ r U2 r′ U′ R U′ R2 r",
      "U′ R′ U′ F′ U′ F R U′ R′ F′ U′ F U′ R",
      "y′ R′ U2 R′ F R F′ U′ F′ U′ F U′ R",
      "l L′ U′ L F2 L′ U′ R U′ R′ M′",
      "y2 R′ M′ U′ R U′ r′ U2 r U′ M",
      "M U′ r U2 r′ U′ R U′ R2 r",
      "L′ U′ L U′ L′ U2 L S′ R U R′ S U′ M′ U R U′ r′",
      "L′ U′ L U′ L′ U2 L R U R′ U′ M′ U R U′ r′ U2 r U R′ U′ M U R U′ R′",
      "U′ f R U R′ U′ f′ U F R U R′ U′ F′",
      "R′ F′ R U′ S r′ F M′ F R S′",
      "M L′ U′ L U′ l′ U2 l U′ M′",
      "y2 r R2 U′ R U′ r′ U2 r U′ M",
      "y2 M′ R′ U′ R U′ r′ U2 r U′ r′ R",
      "y2 r′ U′ R U′ R′ U2 r2 U R′ U′ M U R U′ R′",
      "M r′ F′ r U′ R′ F2 R U′ M′",
      "y′ S U′ R′ U′ R2 U R2 U′ R′ U′ S′",
      "y′ f′ U′ L′ U L f L U F U′ F′ L′",
      "y′ L F2 L2 U2 L F′ L′ U2 L2 F2 L′"
    ]
  },
  {
    "id": "OLL -5",
    "category": "Square Shapes",
    "preview": "../../previews/oll-5.svg",
    "setup": "r′ U′ R U′ R′ U2 r",
    "solutions": [
      "r′ U2 R U R′ U r",
      "F R U R′ U′ F′ U′ F R U R′ U′ F′",
      "y2 R′ F R′ F′ R2 y U′ R U′ R′",
      "y2 R′ U′ R d′ R2 B′ R′ B R′",
      "y2 F R′ F R F2 r′ F2 r",
      "y2 l′ U2 L U L′ U l",
      "y2 R′ F2 r U r′ F R",
      "U2 l′ U2 L U L′ U l",
      "y2 F U′ R2 D R′ U R D′ R2 U F′",
      "y B′ R2 F R F′ R B",
      "y2 R′ F2 L F L′ F R",
      "y′ F′ r2 F r U′ r F",
      "y2 R U′ R2 U′ R U R′ U′ R′ U R2 U′ R2 U′ R U′ R′ U′ B U B′ U2 R′ U R"
    ]
  },
  {
    "id": "OLL -6",
    "category": "Square Shapes",
    "preview": "../../previews/oll-6.svg",
    "setup": "r U R′ U R U2 r′",
    "solutions": [
      "r U2 R′ U′ R U′ r′",
      "y2 R U R2 F R F2 U F",
      "y2 R U R′ U y′ R2 F R F′ R",
      "y′ R′ F R′ F′ R2 B U2 B′",
      "R U′ R′ U2 r U′ r′ U′ r U r′",
      "y2 l U2 L′ U′ L U′ l′",
      "F U′ R2 D R′ U′ R D′ R2 U F′",
      "L F2 l′ U′ l F′ L′",
      "y′ x′ D R2 U′ R′ U R′ D′ x",
      "y2 R B2 r′ U′ r B′ R′",
      "R U R′ U′ R′ F R F′ y S R U R′ U′ R′ F R f′",
      "y B r2 B′ r′ U r′ B′",
      "U2 l U2 L′ U′ L U′ l′",
      "y′ F R2 B′ R′ B R′ F′",
      "L F2 R′ F′ R F′ L′"
    ]
  },
  {
    "id": "OLL -7",
    "category": "Lightning Shapes",
    "preview": "../../previews/oll-7.svg",
    "setup": "r U2 R′ U′ R U′ r′",
    "solutions": [
      "r U R′ U R U2 r′",
      "r U r′ U R U′ R′ r U′ r′",
      "L′ U2 L U2 L F′ L′ F",
      "R U R′ U R U′ R′ U′ M′ U R U′ r′",
      "F R′ F′ R U2 R U2 R′",
      "S′ R U R′ U R U2 R′ U S",
      "y2 l U L′ U L U2 l′",
      "y2 R′ U2 R U2 R f′ U′ f",
      "L F R′ F R F2 L′",
      "y x2 F r D′ r F r2 F′ x2",
      "r′ F2 r U2 L F′ L′ F",
      "y′ F R B′ R B R2 F′"
    ]
  },
  {
    "id": "OLL -8",
    "category": "Lightning Shapes",
    "preview": "../../previews/oll-8.svg",
    "setup": "r′ U2 R U R′ U r y2",
    "solutions": [
      "y2 r′ U′ R U′ R′ U2 r",
      "R U2 R′ U2 R′ F R F′",
      "y2 r′ U′ r U′ R′ U R r′ U r",
      "F′ L F L′ U2 L′ U2 L",
      "l′ U′ L U′ L′ U2 l",
      "R′ F′ r U′ r′ F2 R",
      "R′ F′ r U′ L′ U2 l",
      "U2 L′ B′ R B′ R′ B2 L",
      "y x2 B′ r′ D r′ B′ r2 B x2",
      "R′ F′ R U′ L′ U L R′ F R",
      "U2 r′ U′ R U′ R′ U2 r",
      "y′ B′ R′ F R′ F′ R2 B",
      "R′ F′ L F′ L′ F2 R",
      "y2 L′ B′ L U′ R′ U R L′ B L"
    ]
  },
  {
    "id": "OLL -9",
    "category": "Lightning Shapes",
    "preview": "../../previews/oll-9.svg",
    "setup": "F U R U′ R2 F′ R U R U′ R′ y′",
    "solutions": [
      "y R U R′ U′ R′ F R R U R′ U′ F′",
      "y′ L′ U′ L U′ L F′ L′ F L′ U2 L",
      "y2 F′ U′ F r U′ r′ U r U r′",
      "y2 F′ U′ L′ U L y′ U′ R U′ R′ U2 R",
      "M R U2 R′ U′ R U′ R′ U′ M′",
      "R U2 R′ U′ S′ R U′ R′ S",
      "y2 R′ U′ R U′ R′ U R′ F R F′ U R",
      "y R U R′ F′ R U2 R′ U2 R′ F R U′ R′ F R F′",
      "y R U R′ U′ R′ F R2 U R′ U′ F′",
      "y R′ U′ R y r U′ r′ U r U r′",
      "y R′ U′ R y′ x′ R U′ R′ F R U R′ x",
      "r′ R2 U2 R′ U′ R U′ R′ U′ M′",
      "y R′ F R′ F′ R U R U′ R2 F R F′ R",
      "y2 L′ U′ L U′ L F′ L′ F L′ U L U L F′ L′ F",
      "U R′ U′ R F R′ F′ U F R F′",
      "y′ L′ U′ L y l U′ l′ U l U l′",
      "y′ L′ U′ L y′ L F′ L′ U L F L′",
      "r′ R2 U2 R′ U′ R U′ R′ U′ R′ r",
      "U R U R′ U′ R′ F R2 U R′ U′ F′",
      "y′ r′ F′ r U′ r U′ r′ F r′ F2 r",
      "y R′ U′ R F R′ F′ U F R F′",
      "y R′ U′ R y′ R B′ R′ U R B R′"
    ]
  },
  {
    "id": "OLL -10",
    "category": "Lightning Shapes",
    "preview": "../../previews/oll-10.svg",
    "setup": "R U2 R′ F R′ F′ R U′ R U′ R′",
    "solutions": [
      "R U R′ U R′ F R F′ R U2 R′",
      "y′ f R U R′ U′ f′ U R U R′ U R U2 R′",
      "y F U R U′ R′ F′ U′ R U R′ U R U2 R′",
      "y2 L′ U′ L U L F′ L2 U′ L U F",
      "y F U R U′ R′ y U L′ U L U2 L′",
      "y F U F′ R′ F R U′ R′ F′ R",
      "y R U R′ U R′ F R F′ R U′ R′ U′ R′ F R F′",
      "y M′ R′ U2 R U R′ U R U M",
      "y2 r U R′ U R U′ R′ U′ M U R U′ R′",
      "y R′ U2 R U S′ R′ U R S",
      "y R′ U2 r′ R2 U R′ U R U′ M′",
      "R U R′ U l′ U R U′ l U2 R′",
      "y r R2 U2 R U R′ U R U R r′",
      "R U R′ y R′ F R U′ R′ F′ R",
      "y′ r′ F2 r U S r′ F r S′",
      "y2 L U L′ y′ l′ U l U′ l′ U′ l",
      "y2 r′ F′ r U r U′ r2 F′ r U F",
      "R′ U′ R2 f R f′ U′ R′ U R′ U R",
      "R′ U′ R2 f l U′ R′ B′ l U′ R U z′",
      "y M′ R′ U2 R U R′ U R U r′ R",
      "R U R′ y′ r′ U r U′ r′ U′ r",
      "y′ M L′ U2 L U L′ U L U M′",
      "U r R2 U2 R U R′ U R U R r′",
      "U r R2 U2 R U R′ U R U M",
      "y′ S r′ F2 r U r′ F r U2 S′",
      "y F U F′ l′ U l U′ l′ U′ l",
      "U2 L U L′ F′ L F U′ F′ L′ F",
      "U R U R2 F′ U′ F R2 U′ R2 U2 R",
      "y′ L′ U2 L U S L′ U L S′",
      "y′ l L2 U2 L U L′ U L U M′",
      "y′ R r′ L′ U2 L U L′ U L U M′",
      "y2 L′ U′ L F L′ U2 L U2 L F′ L′ U L F′ L′ F",
      "y′ R U R′ U F′ U F U′ R U2 R′",
      "R U R′ U x R′ U R U′ R x′ U2 R′",
      "y′ f R f′ r′ U r U′ r′ U′ r",
      "y r R2 U2 R U R′ U R U M",
      "y2 L U L′ F′ L F U′ F′ L′ F"
    ]
  },
  {
    "id": "OLL -11",
    "category": "Lightning Shapes",
    "preview": "../../previews/oll-11.svg",
    "setup": "M U′ R U2 R′ U′ R U′ R2 r",
    "solutions": [
      "M R U R′ U R U2 R′ U M′",
      "y2 r U R′ U R′ F R F′ R U2 r′",
      "y F′ L′ U′ L U F U F R U R′ U′ F′",
      "y′ l′ U′ L U′ L′ U2 l U2 L′ U′ L U′ L′ U2 L",
      "y′ l′ U′ L U′ L′ U2 x′ U′ R U′ R′ U2 R",
      "y2 S′ U2 R U R′ U R U2 R′ S",
      "y F R U R′ U′ F′ U r U R′ U R U2 r′",
      "y F′ L′ U′ L U F U′ F′ L′ U′ L U F",
      "S R U R′ U R U2 R′ U2 S′",
      "f U R U′ R2 F′ R U R U′ R′ S′",
      "y S′ U L U L′ U L U2 L′ S",
      "y′ F′ U′ L′ U2 L U′ L′ U′ L U′ L′ U L F",
      "r′ R2 U R′ U R U2 R′ U M′",
      "y′ S U R U R′ U R U2 R′ S′",
      "y2 M′ L U L′ U L U2 L′ U M",
      "R2 r′ U R′ U R U2 R′ U M′",
      "U2 R U R′ U′ R′ F R F′ L′ U′ L U L F′ L′ F",
      "R U R′ U R U′ R′ S′ R U′ R′ S",
      "r′ R2 U R′ U R U2 R′ U R′ r",
      "R U R′ U R U R′ S′ R U R′ S",
      "U2 l′ L2 U L′ U L U2 L′ U M",
      "U2 r U R′ U R′ F R F′ R U2 r′",
      "L′ l R U R′ U R U2 R′ U M′",
      "y2 L F R′ F R′ D R D′ R F2 L′",
      "y′ l′ U′ L U′ L′ U2 B′ l U′ R′ U2 R",
      "y2 R′ L2 F L′ F L F2 L′ F L′ R"
    ]
  },
  {
    "id": "OLL -12",
    "category": "Lightning Shapes",
    "preview": "../../previews/oll-12.svg",
    "setup": "F U R U′ R′ F′ U′ F U R U′ R′ F′",
    "solutions": [
      "y′ M′ R′ U′ R U′ R′ U2 R U′ M",
      "F R U R′ U′ F′ U F R U R′ U′ F′",
      "y2 r U R′ U R U2 r′ U2 R U R′ U R U2 R′",
      "y2 r U R′ U R U2 B r′ U L U2 L′",
      "y′ R′ F′ r U′ r U′ r′ F r′ F2 R",
      "y′ S R′ U′ R U′ R′ U2 R U2 S′",
      "y r′ R U2 R′ U′ R U′ R′ U2 R U M′",
      "y′ S U2 L′ U′ L U′ L′ U2 L S′",
      "y2 F U R U2 R′ U R U R′ U R U′ R′ F′",
      "S U′ R′ U′ R U′ R′ U2 R S′",
      "y f′ U′ L′ U L2 F L′ U′ L′ U L S",
      "R U R′ U′ R′ F R F′ U R U R′ U′ R′ F R F′",
      "y′ R U R2 D′ R U′ R′ D R2 U′ R2 F R F′",
      "y l L2 U′ L U′ L′ U2 L U′ M′",
      "y′ r R2 U′ R U′ R′ U2 R U′ R r′",
      "y′ M′ R′ U′ R U′ R′ U2 R U′ R r′",
      "y M L′ U′ L U′ L′ U2 L U′ M′",
      "y′ r R2 U′ R U′ R′ U2 R U′ r′ R",
      "y S′ U2 R′ U′ R U′ R′ U2 R S",
      "y2 S′ U′ L′ U′ L U′ L′ U2 L S",
      "y S′ L′ U′ L U′ L′ U2 L U2 S",
      "y′ M′ R′ U′ R U′ R′ U2 R U′ r′ R",
      "y S′ r′ F′ r U′ r′ F2 r U2 S",
      "y R r2 F′ r U′ r′ F2 r U′ M′",
      "y′ R2 r U′ R U′ R′ U2 R U′ M",
      "y R u R′ U R′ U′ R u′ R′ U R′ U R",
      "y′ L R2 F′ R F′ R′ F2 R F′ L′ R",
      "y2 r U R′ U R U2 x′ U L′ U L U2 L′",
      "U′ l′ U′ L U′ L F′ L′ F L′ U2 l",
      "U l L2 U′ L U′ L′ U2 L U′ M′",
      "U′ M′ R′ U′ R U′ R′ U2 R U′ M",
      "y′ S U2 r′ F′ r U′ r′ F2 r S′",
      "y2 S′ U′ r′ F′ r U′ r′ F2 r S",
      "y′ R′ F′ r U′ L F′ L′ F r′ F2 R",
      "y′ R2 r U′ R U′ R′ U2 R U′ R r′",
      "y r′ R U2 R′ U′ R U′ R′ U2 R U R′ r",
      "U′ r R2 U′ R U′ R′ U2 R U′ R r′",
      "U l L2 U′ L U′ L′ U2 L U′ L l′",
      "y f′ U′ r′ F r2 U r′ U′ L′ U L S",
      "y′ R′ M′ U′ R U′ R′ U2 R U′ R r′",
      "y′ R B U′ B′ R2 D′ r U r′ D R",
      "y′ r R2 U′ R U′ R′ U2 R U′ M",
      "y U2 r R2 U′ R U′ R′ U2 R U′ M",
      "y′ R U R′ U′ R′ F R2 U′ R′ U R U2 R′ U′ F′"
    ]
  },
  {
    "id": "OLL -13",
    "category": "Knight Move Shapes",
    "preview": "../../previews/oll-13.svg",
    "setup": "F′ U′ F r U′ r′ U r U r′",
    "solutions": [
      "F U R U2 R′ U′ R U R′ F′",
      "r U′ r′ U′ r U r′ F′ U F",
      "F U R U′ R2 F′ R U R U′ R′",
      "R U R′ U′ R′ F R F′ R U R′ U R U2 R′",
      "y2 F R U R′ U′ R U′ R′ U′ R U2 R′ U′ F′",
      "l′ U′ L U l F′ L2 U′ L U F",
      "y2 F R U R2 U′ R F′ R′ U R",
      "F U R U2 R′ F R′ F′ R U F′",
      "y2 R′ U′ R U′ r U R2 U R2 U2 r′",
      "L′ U′ L U R U R′ U′ L F′ L′ F R U R′ U R U′ R′",
      "r U′ r′ U′ r U r′ y L′ U L",
      "r U′ r′ U′ r U r′ y′ R′ U R",
      "L F′ L′ U′ L F L′ F′ U F",
      "y2 f R U R2 U′ R′ U R U′ f′",
      "y2 R B′ R′ U′ R B R′ f′ L f",
      "L F′ L′ U′ L F L′ y′ R′ U R",
      "y2 R B′ R′ U′ R B R′ B′ U B",
      "S R U R′ U R U2 R′ U2 S′ R U R′ U′ M′ U R U′ r′",
      "y x′ U r′ F′ D′ F r U′ r′ D r x",
      "y′ x′ D R′ D′ F′ D R D′ R′ F R x",
      "y2 l U′ l′ U′ l U l′ y′ L′ U L",
      "r U′ r′ U′ r U r′ y z U′ R U",
      "y′ x U R′ U′ B′ U R U′ R′ B R"
    ]
  },
  {
    "id": "OLL -14",
    "category": "Knight Move Shapes",
    "preview": "../../previews/oll-14.svg",
    "setup": "F U F′ R′ F R U′ R′ F′ R",
    "solutions": [
      "R′ F R U R′ F′ R F U′ F′",
      "F′ U′ L′ U L2 F L′ U′ L′ U L",
      "F′ U′ L′ U2 L U L′ U′ L F",
      "r U R′ U′ r′ F R2 U R′ U′ F′",
      "S R U R′ U′ R′ F R2 U R′ U′ f′",
      "R U R′ U r′ U′ R2 U′ R2 U2 r",
      "F′ U′ r′ F2 r U′ F R U′ R′",
      "L′ U′ L U L F′ L′ F L′ U′ L U′ L′ U2 L",
      "y R U R′ U R U′ R′ U R′ F R F′ R U2 R′",
      "l′ U l U l′ U′ l F U′ F′",
      "y2 r′ U r U r′ U′ r y R U′ R′",
      "y2 r′ U r U r′ U′ r f R′ f′",
      "l′ U l U l′ U′ l y′ R U′ R′",
      "R′ F R U R′ F′ R y L U′ L′",
      "F′ U′ r′ F r2 U r′ U′ r′ F r",
      "R′ F R U R′ F′ R y′ R U′ R′",
      "y2 F′ L′ U′ L U L′ U L U L′ U2 L U F",
      "R′ F R U l′ U′ l F U′ F′",
      "y2 r′ U r U L′ B′ L B U′ B′",
      "S′ L′ U′ L U′ L′ U2 L U2 S R U R′ U′ M′ U R U′ r′",
      "y x′ D′ r F U F′ r′ D r U′ r′ x",
      "y2 f′ L′ U′ L2 U L′ f L U′ L′",
      "F R U′ R′ U R2 D R′ U R D′ R2 F′",
      "F R2 U D R2 D′ R′ D R′ U′ D′ R2 F′",
      "y′ x′ U′ R U F U′ R′ U R F′ R′"
    ]
  },
  {
    "id": "OLL -15",
    "category": "Knight Move Shapes",
    "preview": "../../previews/oll-15.svg",
    "setup": "r′ U′ r U′ R′ U R r′ U r",
    "solutions": [
      "r′ U′ r R′ U′ R U r′ U r",
      "y2 F R U R′ U′ F′ R′ U2 R U R′ U R",
      "y2 r′ U r U r′ U′ r y R U R′ U′ R U′ R′",
      "y′ R′ U2 R U R′ F U R U′ R′ F′ R",
      "y2 R U R′ U′ R′ F R2 U R′ U′ R U R′ U′ R U R′ U′ F′",
      "F′ L′ U′ L U F2 U y′ R′ U R U2 R′",
      "y2 l′ U′ l L′ U′ L U l′ U l",
      "r′ U′ M′ U′ R U r′ U r",
      "y2 R′ F′ R L′ U′ L U R′ F R",
      "y2 R′ F′ R r′ F′ r U R′ F R",
      "f U f′ R′ f R U′ R′ f′ R",
      "y2 L F′ L′ F L′ U L U′ L′ U′ L U′ F U F′",
      "y R U R′ U2 S U′ R U R′ S′ R U R′",
      "y2 l′ U′ M U′ L U l′ U l",
      "y2 l′ U′ M U′ L U R′ F R",
      "y2 R′ F′ M F′ r U R′ F R",
      "U2 L F′ L′ F L′ U L U′ L′ U′ L U′ F U F′",
      "U2 l′ U′ R r′ U′ L U R′ F R",
      "U2 l′ U′ l L′ U′ L U l′ U l",
      "y2 R′ F′ L′ R U′ L U R′ F R",
      "F U R U′ R D R′ U′ R D′ R2 U′ R U R′ F′",
      "y z′ B′ U′ S U′ F U B′ R B",
      "L′ B′ L R′ U′ R U L′ B L"
    ]
  },
  {
    "id": "OLL -16",
    "category": "Knight Move Shapes",
    "preview": "../../previews/oll-16.svg",
    "setup": "r U r′ U R U′ R′ r U′ r′",
    "solutions": [
      "r U r′ R U R′ U′ r U′ r′",
      "y2 F R U R′ U′ F′ R U2 R′ U′ R U′ R′",
      "y2 R′ F R U R′ U′ F′ R U′ R′ U2 R",
      "R U R′ U′ R′ F R2 U R′ U′ R′ F′ R U R U′ R′",
      "R U′ R′ S R U′ R′ U S′ U2 R U′ R′",
      "r U M U R′ U′ r U′ r′",
      "y2 l U l′ L U L′ U′ l U′ l′",
      "L F L′ R U R′ U′ L F′ L′",
      "R′ F R F′ R U′ R′ U R U R′ U F′ U′ F",
      "y2 l U M′ U L′ U′ l U′ l′",
      "R f R′ F′ R U R U′ R′ S′ R′",
      "y S′ L′ U′ L U L F′ L′ f l′ U′ L U′ L′ U2 l",
      "y′ R′ F′ R f z′ R′ U′ F U R f′ z",
      "y x r′ B′ r U r′ U′ B U r U′ x′",
      "y2 R B R′ r B r′ U′ R B′ R′",
      "y′ z′ F U S U B′ U′ F R′ F′",
      "y2 R B R′ L U L′ U′ R B′ R′"
    ]
  },
  {
    "id": "OLL -17",
    "category": "Dot Case",
    "preview": "../../previews/oll-17.svg",
    "setup": "F R′ F′ R U2 F R′ F′ R U′ R U′ R′",
    "solutions": [
      "R U R′ U R′ F R F′ U2 R′ F R F′",
      "f R U R′ U′ f′ U′ R U R′ U′ R′ F R F′",
      "l U′ l′ f R2 B R′ U R′ U′ f′",
      "y′ f R U R′ U′ f′ U R U R′ U′ R′ F R F′",
      "y2 F R′ F′ R2 r′ U R U′ R′ U′ M′",
      "y2 F R′ F′ R U S′ R U′ R′ S",
      "y2 F U R U′ R′ F′ U R U R′ U′ R′ F R F′",
      "y F U R U′ R′ F′ U′ R U R′ U′ R′ F R F′",
      "y2 F R U′ R′ U′ R U R′ F′ U R U R′ U′ M′ U R U′ r′",
      "y′ R′ U′ F′ U F R2 U R′ U′ R′ F R F′",
      "y2 F R′ F′ R U R U′ R′ U R U R′ U′ M′ U R U′ r′",
      "y2 F U R′ U′ F′ U F R2 U R′ U′ F′",
      "y L′ U′ L U′ L F′ L′ F U2 L F′ L′ F",
      "y′ F′ r U r′ U′ S r′ F r S′",
      "y2 r U R′ U R U2 r′ U2 r U2 R′ U′ R U′ r′",
      "F′ r U r′ U2 r′ F U′ F U r",
      "y F U R U′ R′ U′ R′ F R F′ R U R′ F′",
      "R′ F R U′ M′ U2 r′ U′ F′ U R",
      "y2 r U′ r′ F U2 F U′ R U′ R′ F′",
      "U2 F R′ F′ R U S′ R U′ R′ S",
      "R B′ R′ f R2 B R′ U R′ U′ f′",
      "y F R′ F′ R U2 R U′ B U′ B′ R′",
      "y R′ F′ U2 F2 U R U′ R′ F′ U2 R",
      "y2 R′ U′ F U R U′ R′ F2 U′ F U R",
      "r U′ r U′ r2 U r2 U r′ R′ U2 R U r′",
      "y′ r′ U r′ U r2 U′ r2 U′ r R U2 R′ U′ r",
      "y′ F R U2 R2 U′ F′ U F R U2 F′",
      "R U R′ U x R′ U R U′ x′ U2 x′ z′ U′ R U R′",
      "B L′ B′ L2 l′ U L U′ L′ U′ M",
      "F′ U′ L′ U L U L F′ L′ F L′ U′ L F",
      "U2 F R′ F′ R2 r′ U R U′ R′ U′ M′",
      "y2 r U′ z U′ R x′ U2 R U′ y R U′ R′ F′",
      "U2 r U′ r′ F U2 F U′ R U′ R′ F′",
      "y′ F′ r U r′ U′ S L′ U L S′",
      "y2 R U2 r′ U′ R U M′ R′ F2 r U r′ F",
      "y2 F R′ F′ R M U R U′ R′ U′ M′"
    ]
  },
  {
    "id": "OLL -18",
    "category": "Dot Case",
    "preview": "../../previews/oll-18.svg",
    "setup": "r′ U2 R U R′ U r2 U2 R′ U′ R U′ r′",
    "solutions": [
      "r U R′ U R U2 r2 U′ R U′ R′ U2 r",
      "y R U2 R′ R′ F R F′ U2 M′ U R U′ r′",
      "y2 F R U R′ U y′ R′ U2 R′ F R F′",
      "y F R U R′ U′ F′ U2 r U R′ U′ r′ R U R U′ R′",
      "y′ F R U R′ U′ F′ U2 F R U R′ U′ R U R′ U′ F′",
      "f U R U′ R′ f′ U l′ U′ L U′ L′ U2 l",
      "y′ F R U R′ U′ F′ y2 F R U R′ U′ R U R′ U′ F′",
      "F R′ F′ R U R U′ R′ U F R U R′ U′ F′",
      "y2 r′ U′ R U′ R′ U2 r2 U R′ U R U2 r′",
      "y F S′ R U′ R′ S R U2 R′ U′ F′",
      "r U R′ U R U2 r′ U2 l′ U′ L U′ L′ U2 l",
      "F R′ F′ R U2 F R′ F′ R U′ R U′ R′",
      "y′ F U R U′ R′ F′ U R U R′ U′ M′ U R U′ r′",
      "y r U′ r′ F U F U′ R U R′ U′ F′",
      "y′ F R U′ R′ U′ R U R′ F′ U′ F R U R′ U′ F′",
      "y2 R U R′ U R′ F R F′ U2 M′ U R U′ r′",
      "R′ U′ F′ U F R2 U R′ U′ M′ U R U′ r′",
      "y R′ F′ U′ F U′ R U2 R f′ U′ f",
      "f R U R′ U′ f′ U′ r U′ r′ U′ r U r′ F′ U F",
      "R D r′ U′ r D′ R′ U′ R2 F R F′ R",
      "y2 R U2 R′ F′ U2 F R U′ R2 F R F′",
      "y′ R′ F R F′ U2 R′ F R F′ U F′ U F",
      "r U R′ U R U2 r′ U2 R U2 R′ U2 R′ F R F′",
      "y F R U R′ U′ F′ U M′ U′ M U2 M′ U′ M",
      "y′ F U R U2 R′ S′ R U R′ S F′",
      "y R U2 R2 F R F′ U′ S R U′ R′ U S′",
      "y′ r′ U′ R U M′ U′ R2 F R F′ U R",
      "y R U2 R′ F′ L′ U2 L F R U2 R′",
      "y2 R2 D′ r U r′ D R2 r′ U r U′ r′ U′ r",
      "y R U2 R2 F R F′ U2 M′ U R U′ r′",
      "l′ U′ L U′ L′ U2 l2 U L′ U L U2 l′",
      "y2 F R U R′ U F′ U2 F′ r U r′",
      "y2 R U R2 F′ U′ F U R U2 R′ F R F′",
      "y R U R′ U′ R′ F R F′ y2 F R′ F′ R U R U′ R′",
      "U R U2 R2 F R F′ U2 M′ U R U′ r′",
      "y′ F U R U′ R′ S F′ R′ F R S′ R′ F′ R",
      "y2 F R U R′ U F′ U2 y′ R′ F R F′",
      "y2 F R U R′ U F′ U2 F′ L F L′",
      "y R U2 R2 F R F′ U2 r R′ U R U′ r′",
      "y R D r′ U r D′ R′ U′ r′ U′ R U M′",
      "y2 F R U R′ U′ F′ U r′ U′ R U′ R′ U2 r",
      "y2 l U L′ U L U2 l2 U′ L U′ L′ U2 l",
      "y R U R′ U L′ U′ L U L F′ L′ F U R′ F R F′",
      "y R f R f′ U R′ U2 R′ F R F′",
      "y2 F R U R′ d R′ U2 R′ F R F′",
      "y2 F′ U′ F U2 L F′ L′ F U F R U′ R2 F′ R",
      "y R′ F R2 U R′ F′ U′ F′ L F L′ U2 F′ U F",
      "y2 F R U R′ y′ U R′ U2 R′ F R F′",
      "y R′ U′ F R′ F′ R2 U M U′ R′ U r",
      "y2 S U R′ U′ R S′ R2 F R F′ U R"
    ]
  },
  {
    "id": "OLL -19",
    "category": "Dot Case",
    "preview": "../../previews/oll-19.svg",
    "setup": "F R′ F′ R M U R U′ R′ U′ M′",
    "solutions": [
      "M U R U R′ U′ M′ R′ F R F′",
      "y S′ R U R′ S U′ R′ F R F′",
      "r′ U2 R U R′ U r2 U2 R′ U′ R U′ r′",
      "y R U R′ U′ R′ F R F′ U2 r U R′ U′ r′ R U R U′ R′",
      "R′ U2 F R U R′ U′ F2 U2 F R",
      "y2 r U2 R′ U′ R U′ r2 U2 R U R′ U r",
      "M U′ L′ U′ L U M′ L F′ L′ F",
      "y2 F R′ F′ R U R U′ R′ U′ F R U R′ U′ F′",
      "y2 F U R U′ R2 F′ U′ F U R U′ F′",
      "y2 F R′ F′ R U R U′ R2 F′ U′ F U R",
      "y S R U R′ U′ R′ F R f′ U R U R′ U′ M′ U R U′ r′",
      "y′ F U2 R′ F′ U′ F U R2 U2 R′ F′",
      "y′ S r′ F′ r S′ U r U′ r′ F",
      "r′ R U R U R′ U′ r R2 F R F′",
      "r′ R U R U R′ U′ M′ R′ F R F′",
      "M U R U R′ U′ r R2 F R F′",
      "R r′ U R U R′ U′ M′ R′ F R F′",
      "U R U R′ F′ U′ R U R′ U′ R′ F R U′ M′ U R U′ r′",
      "r′ R U R U R′ U′ R2 r F R F′",
      "U2 F R′ F′ R U R U′ R′ U′ F R U R′ U′ F′",
      "y2 l′ U2 L U L′ U l2 U2 L′ U′ L U′ l′"
    ]
  },
  {
    "id": "OLL -20",
    "category": "Dot Case",
    "preview": "../../previews/oll-20.svg",
    "setup": "r U R′ U′ M2 U R U′ R′ U′ M′",
    "solutions": [
      "M U R U R′ U′ M2 U R U′ r′",
      "f R U R′ U′ f′ R′ U′ R′ F R F′ U R",
      "S R′ U′ R U R U R U′ R′ S′",
      "S′ R U R′ S2 R U′ R′ U S′",
      "S′ R U R′ S U′ M′ U R U′ r′",
      "R U R′ U′ R′ F R F′ R U2 R2 F R F′ R U2 R′",
      "S R U R′ U′ R′ U′ R′ U R S′",
      "F U R U′ R′ F′ U2 R′ U′ R′ F R F′ U R",
      "r U R′ U′ M U R U′ R′ y R U R′ U′ M′ U R U′ r′",
      "r U R′ U′ M U S′ R U′ R′ S",
      "M′ U M′ U M′ U M′ U′ M′ U M′ U M′ U M′",
      "M′ U2 M U2 M′ U′ M U2 M′ U2 M",
      "l′ U′ L U M2 U′ L′ U L U M′",
      "M U2 M′ U2 M U M′ U2 M U2 M′",
      "M′ U′ M′ U′ M′ U′ M′ U M′ U′ M′ U′ M′ U′ M′",
      "M′ U2 M U2 M′ U M U2 M′ U2 M",
      "M′ U′ M U2 M′ U′ M U′ M′ U′ M U2 M′ U′ M",
      "R U′ R2 F2 U′ R F R′ U F2 R2 U R′",
      "M′ U′ M′ U′ M′ U′ M′ U M′ U′ M′ U′ M′ U′ M′ U′",
      "r′ R U R U R′ U′ R2 r2 U R U′ r′",
      "S U′ R U R′ S2 R U′ R′ S",
      "M U M F R′ F′ M2 F R F′",
      "R2 S′ R2 U′ S2 U′ R2 S′ R2",
      "r U R′ U′ r2 R2 U R U′ R′ U′ M′",
      "M U′ L′ U′ L U M2 U′ L′ U l",
      "r′ R U R U R′ U′ L2 l2 U R U′ r′",
      "r′ R U R U R′ U′ M2 U R U′ r′",
      "M′ U′ M U r U R′ U′ M U R U′ R′ U2 M′ U2 M",
      "r U R′ U′ r′ R U S′ R U′ R′ S",
      "R U2 R′ U′ R U′ R r′ U R′ U r U2 r′ U M′",
      "U M′ U M′ U M′ U M′ U′ M′ U M′ U M′ U M′",
      "R′ F R S2 R′ F′ R S′ U S′",
      "r U R′ U′ r2 R2 U R U′ R′ U′ R′ r",
      "M U M U M U M U M′ U M′ U M′ U M′ U",
      "r′ R U R U R′ U′ R′ M′ r U R U′ r′",
      "r U R′ U′ r2 R2 U R U′ R′ U′ r R′",
      "M′ U2 M′ U2 M′ U M U2 M U2 M U",
      "r U R′ U′ r R′ M′ U R U′ R′ U′ M′",
      "r U R′ U′ R′ M′ r U R U′ R′ U′ M′",
      "M′ U′ M′ U′ M′ U′ M′ U′ M U′ M U′ M U′ M U′",
      "M U R U R′ U′ L2 l2 U R U′ r′",
      "L R′ F2 L′ R U2 L R′ F L′ R U2 L R′ F2 L′ R",
      "r′ R U R U R′ U′ r2 R2 U R U′ r′"
    ]
  },
  {
    "id": "OLL -21",
    "category": "OCLL",
    "preview": "../../previews/oll-21.svg",
    "setup": "R U R′ U R U′ R′ U R U2 R′ y′",
    "solutions": [
      "y R U2 R′ U′ R U R′ U′ R U′ R′",
      "y′ F R U R′ U′ R U R′ U′ R U R′ U′ F′",
      "y F R U R′ U′ R U R′ U′ R U R′ U′ F′",
      "R U R′ U R U′ R′ U R U2 R′",
      "L U L′ U L U′ L′ U L U2 L′",
      "R U R′ U R U L′ U R′ U′ L",
      "R′ U′ R U′ R′ U R U′ R′ U2 R",
      "y F U R U′ R′ U R U′ R′ U R U′ R′ F′",
      "y f R U R′ U′ R U R′ U′ R U R′ U′ f′",
      "y R′ U2 R U R′ U′ R U R′ U R",
      "y L′ U2 L U L′ U′ L U L′ U L",
      "R′ F′ R U2 R U2 R′ F U′ R U′ R′",
      "y F R U R′ U′ R U R′ U′ R U R′ U′ F′ y′",
      "y f U R U′ R′ U R U′ R′ U R U′ R′ f′",
      "U F R U R′ U′ R U R′ U′ R U R′ U′ F′",
      "y R′ F2 R2 U2 R′ F2 R U2 R2 F2 R",
      "L′ U R U′ L U R′ U′ R U2 R′ U′ R U′ R′",
      "R B U B′ U′ B U B′ U′ B U B′ U′ R′",
      "U R U2 R′ U′ R U R′ U′ R U′ R′",
      "U R U2 R′ U′ R U R′ U2 R′ F R2 U′ R′ U′ R U R′ F′ U2",
      "U′ f R U R′ U′ R U R′ U′ R U R′ U′ f′",
      "f R U R′ U′ R F′ R U R′ U′ R′ S′",
      "R U R′ U R U r′ F R′ F′ r"
    ]
  },
  {
    "id": "OLL -22",
    "category": "OCLL",
    "preview": "../../previews/oll-22.svg",
    "setup": "R′ U2 R2 U R2 U R2 U2 R′",
    "solutions": [
      "R U2 R2 U′ R2 U′ R2 U′ U′ R",
      "f R U R′ U′ S′ R U R′ U′ F′",
      "R U R′ U′ R′ F R2 U R′ U′ R U R′ U′ F′",
      "R U′ z U′ R D′ R U R U′ R U z′",
      "R′ U′ F′ R U R′ U′ R′ F R2 U2 R′ U2 R",
      "R U R′ U R U2 R′ U′ R U R′ U R U2 R′",
      "y2 L′ U R U′ L U′ R′ U′ R U′ R′",
      "y′ R U R′ U F′ R U2 R′ U2 R′ F R",
      "R2 D′ R U R′ D R U R U′ R′ U R U R′ U R",
      "F R U R′ U′ R U R′ U′ F′ R U R′ U′ M′ U R U′ r′",
      "y F R2 U′ R2 U R2 U S R2 f′",
      "y R U R′ U R U2 R2 U2 R U R′ U R",
      "y′ R′ U′ R U′ R′ U2 R2 U2 R′ U′ R U′ R′",
      "y x′ R U R′ D R U′ R′ D′ R U′ R′ D R U R′ D′ x",
      "y2 F U R U′ R′ F′ U2 F R U R′ U′ F′",
      "R′ F′ U′ F U′ R U S′ R′ U R S",
      "y′ R U2 R′ U R′ D′ R U2 R′ D R2 U′ R′",
      "y2 F R U R′ U′ R U R′ U′ S R U R′ U′ R U R′ U′ f′",
      "R U2 R2 U′ R2 U′ R2 U2 R",
      "f R U R′ U′ f′ F R U R′ U′ F′",
      "y2 L′ U2 L2 U L2 U L2 U2 L′",
      "F S R U R′ U′ S′ R U R′ U′ F′",
      "y2 r′ F2 r2 B r2 F r2 B2 r′",
      "y2 L U2 L2 U′ L2 U′ L2 U2 L",
      "y R U R′ U′ L′ U′ L U′ L′ U L U′ R U′ R′ U L′ U L",
      "U′ F U R U2 R′ U R U R′ F′ R U2 R′ U′ R U′ R′",
      "R′ U2 R U R′ U R U R′ U2 R U R′ U R U",
      "y2 F U R U′ R′ S U R U′ R′ f′",
      "y2 L U′ R′ U L′ U R U R′ U R",
      "y2 r′ F R F′ r U′ R′ U′ R U′ R′"
    ]
  },
  {
    "id": "OLL -23",
    "category": "OCLL",
    "preview": "../../previews/oll-23.svg",
    "setup": "R U2 R D R′ U2 R D′ R2",
    "solutions": [
      "y2 R2 D′ R U2 R′ D R U2 R",
      "R2 D R′ U2 R D′ R′ U2 R′",
      "y2 R′ U′ R U′ R′ U2 R2 U R′ U R U2 R′",
      "R U R′ U R U2 R2 U′ R U′ R′ U2 R",
      "y2 R′ U2 R F U′ R′ U′ R U F′",
      "y2 R′ F R U′ R′ U′ R U R′ F′ R U R′ U′ R′ F R F′ R",
      "R U R′ U R U2 R′ U R U2 R′ U′ R U′ R′",
      "y′ R U2 R′ U′ R U′ R′ L′ U2 L U L′ U L",
      "y′ R U2 R′ U′ R U′ R′ U′ R U R′ U R U2 R′",
      "y R U R′ U′ R U′ R′ U2 R U′ R′ U2 R U R′",
      "y F2 R U′ R′ U′ R U R′ F′ R U R′ U′ R′ F R F2",
      "R U R′ U R U2 R′ U2 L′ U′ L U′ L′ U2 L",
      "y F U2 F′ R′ U F U F′ U′ R",
      "y′ R2 D′ R U′ R′ D R2 U′ R′ U2 R",
      "y2 R′ U2 R U2 R′ F′ R U R′ U′ R′ F R2",
      "y2 x′ R U′ R′ D R U2 R′ D′ R U′ R′",
      "y F R U R′ U′ R U R′ U′ F2 L′ U′ L U F",
      "R U R′ U R U2 R′ y R U2 R′ U′ R U′ R′",
      "y2 R′ U2 R F′ R′ F U2 F′ R F",
      "y2 R U R′ U′ R′ F2 R2 U′ R′ U′ R U R′ F2",
      "R U2 R′ U L′ U2 R U′ R′ U2 L",
      "R U2 x R U2 R U2 R′ U2 L U2 r′ U2 R U2 R′ U2 R′",
      "R2 B2 U2 L U2 R′ U2 R U2 F2 R F2 L′ B2 R2",
      "R U′ L U′ R′ U L′ U2 R U′ R′",
      "R U′ L′ U R′ U′ L U2 L′ U R U′ L U R′",
      "R U2 x R U2 R U2 r′ U2 L U2 R′ U2 R U2 R′ U2 R′",
      "R2 D R′ U2 R D′ R′ U2 D D′ R′",
      "L2 D′ L U2 L′ D L U2 L",
      "R U R′ U R U2 R′ y R U2 R′ U′ R U′ R′ U",
      "U2 R2 D′ R U R′ D R U R U′ R′ U′ R",
      "U r U R′ U′ r′ F R F′ R′ F′ L′ F R F′ L F",
      "R′ D R D′ R′ D R U′ R′ D′ R D R′ D′ R U",
      "y2 R′ F R2 U′ r′ F R′ F′ r U R′ F′ R",
      "y2 L2 D L′ U2 L D′ L′ U2 L′",
      "y2 z U R2 U′ F′ R U R U′ R′ F z′",
      "U2 R′ F R U′ R′ U′ R U R′ F′ R U R′ U′ R′ F R F′ R",
      "R′ U2 L F2 L′ F2 R2 U2 R U2 R′ U2 F2 R2 F2",
      "U′ R U2 R′ U′ R U′ R′ U′ R U R′ U R U2 R′",
      "x2 R2 U R′ D2 R U′ R′ D2 R′ x2",
      "U′ R′ U′ R U′ R′ U2 R U′ R′ U2 R′ D′ R U2 R′ D R2 U",
      "R2 D R′ U2 R D′ R′ U R U R U R U′ R′ U′ R2 U2",
      "U′ R U2 R′ U′ R U′ R′ U2 R′ U2 R U R′ U R",
      "U′ R′ U R′ D′ U′ R U′ R′ U2 R U′ R′ D R U′ R U′",
      "y2 r U′ r2 F R F′ r U R′ U′ r U r′",
      "x R2 F R′ B2 R F′ R′ B2 R′",
      "L′ U′ L U′ L′ U2 L2 U L′ U L U2 L′"
    ]
  },
  {
    "id": "OLL -24",
    "category": "OCLL",
    "preview": "../../previews/oll-24.svg",
    "setup": "F R′ F′ r U R U′ r′",
    "solutions": [
      "r U R′ U′ r′ F R F′",
      "y′ x′ R U R′ D R U′ R′ D′ x",
      "y2 R′ F′ r U R U′ r′ F",
      "y′ F R U R′ U′ R U′ R′ U′ R U R′ F′",
      "y′ L′ U L U2 R′ L′ U L U′ R",
      "y2 L U L′ U L U2 L′ R′ U′ R U′ R′ U2 R",
      "y′ R′ U′ R′ D′ R U R′ D R2",
      "y R U R D R′ U′ R D′ R2",
      "R U R′ U′ L′ U R U′ R′ L",
      "y R U2 R′ U′ R U′ R′ U R U R′ U R U2 R′",
      "y′ r′ U′ L D′ L′ U L D x",
      "y′ R′ U2 R U R′ U R2 U2 R′ U′ R U′ R′",
      "y2 F U R U2 R′ U R U R′ F′",
      "R′ U′ R U′ R′ U2 R U2 R U R′ U R U2 R′",
      "y2 L′ U′ L U R U′ L′ U L R′",
      "y R′ F′ R U R′ U′ R′ F R U R",
      "y′ R U′ R′ U2 R U R′ U2 R U R′ U R U′ R′",
      "L F R′ F′ L′ F R F′",
      "y2 l′ U′ L U R U′ r′ F",
      "r U R′ U′ L′ U R U′",
      "x L U R′ U′ L′ U R U′",
      "x U R U′ L U R′ U′ L′ x′",
      "U′ x′ R U R′ D R U′ R′ D′ x",
      "F R F′ r U R′ U′ r′",
      "U R′ F′ R U R′ U′ R′ F R U R",
      "y2 l′ U′ L U l F′ L′ F",
      "U′ F R′ D′ R U R′ D R U′ F′",
      "r U′ r′ U2 r U r′ y′ R′ F′ U2 F R",
      "r U′ r′ U2 r U r′ y L′ B′ U2 B L",
      "y2 R′ F′ L F R F′ L′ F",
      "y2 x R′ U′ L U R U′ L′ U x′",
      "y′ x′ D R U′ R′ D′ R U R′ x",
      "y′ x′ D R U′ R′ D′ R U R′",
      "y2 l′ U′ L U R U′ L′ x′ F",
      "y2 l′ U′ L U R U′ L′ U x′",
      "y x R′ U′ R D′ R′ U R D x′",
      "y l′ U′ R D′ R′ U R D x′",
      "y B′ R′ F R B R′ F′ R",
      "U R U R D R′ U′ R D′ R2",
      "U2 R′ F′ L F R F′ L′ F",
      "U′ R′ U′ R′ D′ R U R′ D R2",
      "y F′ U R U′ L′ U R′ U′ L F",
      "x L U R′ U′ L′ U R U′ x′",
      "r U R′ U′ r′ F R F′ U",
      "U F R U′ R′ U′ R U2 R′ U′ F′ R′ U′ R U′ R′ U2 R U",
      "U R′ U D′ R U2 R′ D R′ U′ R U2 R′ U′ R2",
      "U2 R U′ R2 D′ r U2 r′ D R2 U′ R′ U′ R U′ R′",
      "y2 x′ R U L′ U′ R′ U L U′",
      "r U R′ U′ L′ U l F′",
      "x′ L D R′ D′ L′ D R D′ x",
      "y′ F R B′ R′ F′ R B R′",
      "R′ U′ R F R′ U R U′ F′",
      "r U R′ U′ z U′ R z′ R U′",
      "r′ U′ R U r f′ U′ f"
    ]
  },
  {
    "id": "OLL -25",
    "category": "OCLL",
    "preview": "../../previews/oll-25.svg",
    "setup": "R′ F′ r U R U′ r′ F y′",
    "solutions": [
      "y F′ r U R′ U′ r′ F R",
      "F R′ F′ r U R U′ r′",
      "y L′ U2 L′ D′ L U2 L′ D L2",
      "R U2 R D R′ U2 R D′ R2",
      "r U2 R2 F R F′ R U2 r′",
      "y2 R U2 R′ U′ R U R′ U′ R U R′ U′ R U′ R′",
      "L U L′ U L U′ L′ U L U′ L′ U L U2 L′",
      "y2 R′ F′ L′ F R F′ L F",
      "L′ R U R′ U′ L U R U′ R′",
      "y2 R′ U′ R U R′ F′ R U R′ U′ R′ F R2",
      "y2 R2 D′ R U′ R′ D R U R",
      "y′ x L U R U′ L′ U R′ U′",
      "y′ R U R′ U′ R′ F R U R U′ R′ F′",
      "y R′ U′ R U′ R′ U R U′ R′ U R U′ R′ U2 R",
      "y R2 D R′ U R D′ R′ U′ R′",
      "y2 F R U′ R′ U′ R U2 R′ U′ F′",
      "R U2 R′ U′ R U′ R′ U2 R U R′ U R U2 R′",
      "y′ R′ F′ R U R′ U′ R′ F R2 U′ R′ U2 R",
      "L′ U′ L U′ B U′ L′ U′ L U B′",
      "y′ R′ U′ R′ D′ R U′ R′ D R U2 R",
      "y B′ R U R′ U′ R′ F R2 U′ R′ U′ R U R′ F′ B",
      "R′ F R U R′ U′ R′ F′ R U R",
      "y2 R′ F′ R U R′ U′ R′ F R U′ R U R′ U R",
      "y2 r U2 R′ U′ R U R′ U′ R U R′ U′ R U′ r′",
      "y′ R2 F′ R U R U′ R′ F R U′ R′ U R",
      "y′ R′ F R2 U′ R′ U′ R U R′ F′ R U′ R′ U R U R′",
      "R′ F R B′ R′ F′ R B",
      "x R′ U R D′ R′ U′ R D x′",
      "y′ x′ R U′ R′ D R U R′ D′ x",
      "y2 l′ U′ L′ U R U′ L U x′",
      "M F R′ F′ r U R U′ R′",
      "x U R′ U′ L U R U′ L′ x′",
      "U′ R U R′ U′ R′ F R U R U′ R′ F′",
      "y2 x U R D R′ U′ R D′ R′",
      "U F′ r U R′ U′ r′ F R",
      "y2 R U R′ U R U′ R′ U R U′ R′ U R U2 R′",
      "F l′ U′ L U R U′ r′",
      "U R U2 R2 D′ R U′ R′ D R2 U′ R′",
      "y′ R′ U2 R′ D′ R U2 R′ D R2",
      "x R′ U R D′ R′ U′ R D",
      "y r2 U r′ U′ r′ F r2 U′ r′ U′ r U r′ F′ U r′",
      "U B′ R′ F′ R B R′ F R",
      "U2 R′ U′ F U F′ R F U′ F′",
      "y F′ L F l′ U′ L′ U l",
      "l′ U R D′ R′ U′ R D x′",
      "y2 F R B R′ F′ l U′ l′",
      "y F′ r U R′ U′ L′ U R",
      "U R2 D R′ U R D′ R′ U′ R′",
      "U2 R2 D′ R U′ R′ D R U R",
      "y2 x′ D R U R′ D′ R U′ R′",
      "U′ x′ R U′ R′ D R U R′ D′ x",
      "U F R U R′ U′ R′ F′ U′ R U R U′ R′ U′ R′ U R",
      "R U R D R′ U2 R D′ R′ U′ R′ U R U R′ U",
      "R2 U′ R U R U′ R D′ U R U′ R′ D U′",
      "U′ R′ U2 R′ D′ R U2 R′ D R2",
      "R2 D′ R U2 R′ D R U2 R2 U2 R′ U′ R U′ R′ U",
      "R U2 R D r′ U2 r D′ R2 U2",
      "y2 L′ B L F′ L′ B′ L F",
      "x′ R′ D R U′ R′ D′ R U",
      "y2 R′ F R U R′ U′ R U R′ U′ F′ U R f R f′",
      "y′ r U R U′ r′ F R′ F′",
      "y x′ R U L U′ R′ U L′ U′",
      "U2 R′ F′ L′ F R F′ L F",
      "y′ L F R F′ L′ F R′ F′",
      "F R′ F′ L F R F′ L′",
      "y F′ L F R′ F′ L′ F R",
      "y′ r U R U′ L′ U R′ U′",
      "y′ l U′ R′ D R U R′ D′ x",
      "y2 F R B R′ F′ R B′ R′",
      "y2 F U R′ U′ R F′ R′ U R"
    ]
  },
  {
    "id": "OLL -26",
    "category": "OCLL",
    "preview": "../../previews/oll-26.svg",
    "setup": "R U R′ U R U2 R′ y′",
    "solutions": [
      "R′ U′ R U′ R′ U2 R",
      "y R U2 R′ U′ R U′ R′",
      "y2 L′ U R U′ L U R′",
      "y′ M′ U′ r′ F R F′ r U r′",
      "y2 L′ U′ L U′ L′ U2 L",
      "y′ L U2 L′ U′ L U′ L′",
      "U R U2 R′ U′ R U′ R′",
      "y R U2 D2 R′ U′ R U′ R′ U2 R D2 R′ U",
      "y2 U′ R U2 R′ U′ R U′ R′",
      "R′ U L U′ R U L′",
      "U2 L′ U R U′ L U R′",
      "U2 L′ U′ L U′ L′ U2 L",
      "y2 r′ F′ r U′ r′ F2 r",
      "y2 L′ U′ L U′ L′ U2 L y2"
    ]
  },
  {
    "id": "OLL -27",
    "category": "OCLL",
    "preview": "../../previews/oll-27.svg",
    "setup": "R U2 R′ U′ R U′ R′",
    "solutions": [
      "R U R′ U R U2 R′",
      "y′ R′ U2 R U R′ U R",
      "R U′ L′ U R′ U′ L",
      "r U′ r′ F R′ F′ r U M",
      "y L′ U2 L U L′ U L",
      "y2 L U L′ U L U2 L′",
      "y F U F′ U F U2 F′",
      "y′ U R U′ L′ U R′ U′ L",
      "y′ R U′ R′ U′ R U′ R′ U′ R U′ R′ U′ R U R′",
      "U L′ U2 L U L′ U L",
      "R U′ r′ F R′ F′ r",
      "U′ R′ U2 R U R′ U R",
      "y r′ F2 r U L′ U L"
    ]
  },
  {
    "id": "OLL -28",
    "category": "All Corner Oriented",
    "preview": "../../previews/oll-28.svg",
    "setup": "R U R′ U′ M′ U R U′ r′",
    "solutions": [
      "r U R′ U′ M U R U′ R′",
      "r U R′ U′ r′ F R2 U′ R′ U′ R U R′ F′",
      "y2 M′ U M U2 M′ U M",
      "y′ M′ U′ M U2 M′ U′ M",
      "F R U R′ U′ F′ U2 F R U R′ U′ F′",
      "R U R′ U′ M′ U R U′ r′ R U R′ U′ M′ U R U′ r′",
      "y′ r′ U′ R U M′ U′ R′ U R",
      "y2 f U R U′ R′ S′ R U R′ U′ F′",
      "R′ F R S R′ F′ R S′",
      "S′ R U R′ S R U′ R′",
      "F R U R′ U′ F2 L′ U′ L U F",
      "y r U R′ F′ R U R′ U′ R′ F R2 U′ r′",
      "M′ U′ M U′ M′ U′ M U′ M′ U′ M",
      "y′ M U R U R′ U′ M′ U R U′ R′",
      "y′ S′ R U′ R′ S R U R′",
      "y′ M R U R′ F′ R U R′ U′ R′ F R2 U′ R′ U′ M′",
      "y2 r2 D′ r U′ r′ D r2 F′ r′ U r F",
      "r U R′ U′ r′ R U R U′ R′",
      "M U M′ U2 M U M′",
      "y M U′ M′ U2 M U′ M′",
      "U′ M′ U′ M U2 M′ U′ M",
      "U r′ U r2 U′ r2 U′ r2 U r2 U r2 U′ r2 U′ r2 U r′",
      "U′ r′ U′ R U M′ U′ R′ U R",
      "U′ R U R′ F′ R U R′ F′ R U R′ U′ R′ F R2 U′ R′ U′ F R U′ R′",
      "y l′ U′ L U l L′ U′ L′ U L",
      "U r U R′ F′ R U R′ U′ R′ F R2 U′ r′",
      "y′ r U′ r′ U′ r U r′ R U2 R′ r U′ r′ U r U r′",
      "y′ M U M′ U M U M′ U M U M′ U",
      "R F D2 r2 D2 F r2 D2 R",
      "y′ L R′ F′ L′ R U2 L R′ F′ L′ R",
      "y l′ U′ L U M U′ L′ U L"
    ]
  },
  {
    "id": "OLL -29",
    "category": "Awkward Shapes",
    "preview": "../../previews/oll-29.svg",
    "setup": "M F R′ F′ R U R U′ R′ U′ M′",
    "solutions": [
      "y R U R′ U′ R U′ R′ F′ U′ F R U R′",
      "r2 D′ r U r′ D r2 U′ r′ U′ r",
      "M U R U R′ U′ R′ F R F′ M′",
      "R′ U′ R U′ R′ U2 F R U R′ U′ F′ U R",
      "y2 R′ F R F′ R U2 R′ U′ F′ U′ F",
      "y r U R′ U′ M r′ F R F′ M′",
      "y R U R′ U′ R′ F R F′ R U R′ U′ M′ U R U′ r′",
      "y l D l′ U l D′ l2 U l U′ l′ U′ l",
      "f′ L′ U′ L U S r U R′ U′ r′ F R",
      "y2 F′ U′ L′ U2 L U L′ U2 L U F",
      "y′ R U2 R2 F R F′ R U′ R′ U R U2 R′",
      "y F R U R′ U′ F′ L′ U′ L U L F′ L′ F",
      "y S′ R U R′ U′ R′ F R F′ U S",
      "y′ f U R U′ R′ f′ R U R′ U′ R′ F R F′",
      "y′ R U R′ U R U2 R′ U R U R′ U′ R′ F R F′",
      "y2 F′ r U′ r2 F r U r′ F′ r F2",
      "y R′ U2 R2 U R′ U′ R′ U2 F R F′",
      "y x R′ U′ R D′ R′ U2 R′ U′ R2 D x′",
      "y2 F R′ U′ R2 U′ R2 U2 R U′ F′",
      "y L′ U′ L U L F′ L2 U L U L′ U′ L U′ L′ U L F",
      "y′ r D r′ U r D′ r2 U r U′ r′ U′ r",
      "y R F R′ U R F′ R2 F R U′ R′ F′ R",
      "y2 R′ F R U′ R′ U R U2 R′ U′ F′ U2 R",
      "y2 R2 U′ R F R′ U R2 U′ R′ F′ R",
      "y r U R′ U′ M2 R′ F R F′ M′",
      "y R′ F R′ F r U′ R U′ R U′ r′ F",
      "y2 R′ U′ F U R U′ R′ F′ U2 R U R′ U R",
      "y2 R′ F R F′ R U2 R′ d′ L′ U′ L",
      "y2 R′ F R F′ R U2 R′ U′ y L′ U′ L",
      "r D r′ U′ r D′ r′ U r′ U′ R U M′",
      "y R U R′ F′ U′ S′ F R U′ R′ S",
      "r′ R U R U R′ U′ R′ F R F′ M′",
      "L2 U′ L B L′ U L2 U′ r′ U′ r",
      "y2 F′ z R′ U′ R2 U R U′ R2 U R F z′",
      "x′ U′ R U′ R2 F x R U R′ U′ R B2",
      "y2 F′ L F′ L2 U L U L′ U′ L F2"
    ]
  },
  {
    "id": "OLL -30",
    "category": "Awkward Shapes",
    "preview": "../../previews/oll-30.svg",
    "setup": "F U R U2 R′ U R U2 R′ U′ F′ y2",
    "solutions": [
      "y2 F U R U2 R′ U′ R U2 R′ U′ F′",
      "y′ r′ D′ r U′ r′ D r2 U′ r′ U r U r′",
      "y2 F R′ F R2 U′ R′ U′ R U R′ F2",
      "y′ L′ U′ L U L′ U L F U F′ L′ U′ L",
      "y2 R U R′ U R U′ R′ F′ U′ F U R U2 R′",
      "f R U R′ U′ S′ R′ F′ r U R U′ r′",
      "M U′ L′ U′ L U L F′ L′ F M′",
      "l2 D l′ U′ l D′ l2 U l U l′",
      "y′ F′ L′ U′ L U F R U R′ U′ R′ F R F′",
      "y2 L F′ L′ F L′ U2 L U F U F′",
      "y′ R′ F′ r U M R U′ r′ F M′",
      "y′ S L′ U′ L U L F′ L′ F U′ S′",
      "y2 F U R U′ R2 F′ R U R U′ R′ F R U R′ U′ F′",
      "y′ x L U L′ D L U2 L U L2 D′ x′",
      "y′ r U2 R2 F R F′ R U′ R′ U R U2 r′",
      "y′ R U R′ U′ R′ F R2 U′ R′ U′ R U R′ U R U′ R′ F′",
      "y L′ U2 L2 F′ L′ F L′ U L U′ L′ U2 L",
      "f R U R2 U′ R′ U R2 U′ R′ f′",
      "y′ S U2 F R U′ R′ U R U R′ f′",
      "R2 U R′ B′ R U′ R2 U R B R′",
      "y2 r2 D r′ U′ r D′ r2 U r U r′",
      "U′ F R U′ R′ U R U R′ U R U′ R′ U R U′ R′ F′",
      "U′ r′ D′ r U′ r′ D r2 U′ r′ U r U r′",
      "R U R′ U R U′ R′ U R U′ B U′ B′ R′",
      "U M f R f′ U′ r′ U′ R U M′ U M′",
      "U2 F U R U2 R′ U′ R U2 R′ U′ F′",
      "y S′ R′ U′ R U R f′ U′ f U′ S",
      "l L′ U′ L′ U′ L U L F′ L′ F M′",
      "y2 M′ U′ R′ U′ R U R B′ R′ B M",
      "y2 R U R U′ R′ F U R2 U′ F′ R′ U R",
      "y′ L′ F′ L U′ L′ F L2 F′ L′ U L F L′",
      "y S′ F R U′ R′ U R U R′ F′ U2 S",
      "y′ R′ F′ r U r′ R2 U′ r′ F M′",
      "y2 L2 U L′ F′ L U′ L2 U L F L′",
      "R2 U R′ B′ R U′ R2 U l U l′"
    ]
  },
  {
    "id": "OLL -31",
    "category": "P Shapes",
    "preview": "../../previews/oll-31.svg",
    "setup": "R′ F R U R′ U′ F′ U R",
    "solutions": [
      "R′ U′ F U R U′ R′ F′ R",
      "y2 S′ L′ U′ L U L F′ L′ f",
      "y′ F U R U′ R′ F2 r U R′ U′ r′ F R",
      "y S R U R′ U′ f′ U′ F",
      "y′ F R′ F′ R U R U R′ U′ R U′ R′",
      "y2 R′ F R U R′ U′ F2 U F R",
      "y2 L′ U2 L U F U′ F′ L′ U L",
      "F′ U′ L′ U L F l′ U′ L U l F′ L′ F",
      "R′ U f R U R′ U′ f′ U2 R",
      "y2 S′ r′ F′ r U r U′ r′ f",
      "y2 r′ F′ U F r U′ r′ U′ r",
      "y2 L′ U′ B U L U′ L′ B′ L",
      "y′ R′ U r′ D′ r U′ r′ D r U′ R",
      "y2 F f′ L′ U′ L U L F′ L′ f y2",
      "R′ d′ L d R U′ R′ F′ R",
      "y′ R′ U′ r′ D′ r U r′ D r R",
      "U2 S′ L′ U′ L U L F′ L′ f",
      "R′ U′ F U R U′ R′ F′ R U",
      "M′ f R f′ U′ r′ U′ R",
      "z′ U′ L′ F L U L′ U′ F′ U"
    ]
  },
  {
    "id": "OLL -32",
    "category": "P Shapes",
    "preview": "../../previews/oll-32.svg",
    "setup": "f R′ F′ R U R U′ R′ S′",
    "solutions": [
      "S R U R′ U′ R′ F R f′",
      "y2 L U F′ U′ L′ U L F L′",
      "y2 F U R U′ R′ F′ r U R′ U′ r′ F R F′",
      "R U2 R′ U′ F′ U F R U′ R′",
      "y′ F′ r U r′ U′ r′ F′ r U r′ F r",
      "y2 F U R U′ F′ r U R′ U′ r′",
      "y S′ r′ F′ r U f U F′",
      "y2 x′ R U′ R′ D R U R U′ R′ U R′ D′ x",
      "y2 x′ R U R′ D R U′ R U′ R′ U R′ D′ x",
      "y′ R′ F R F′ U′ r U′ r′ U r U r′",
      "y2 z u′ R2 U R U2 R D R′ U R z x′",
      "y′ M′ U R U R′ U′ R′ F R F′ U′ M",
      "y R U r D r′ U′ r D′ r′ R′",
      "R U B′ U′ R′ U R B R′",
      "y F U R′ U′ F′ U F R F′",
      "y R U′ r D r′ U r D′ r′ U R′",
      "y2 x′ r U F′ U′ r′ F r F r′ x",
      "y2 z U R F′ R′ U′ R z′ r U r′",
      "l F U′ F′ l′ U l U l′",
      "y′ R′ U′ F D U R U′ R′ D′ F′ R",
      "F′ f R U R′ U′ R′ F R f′",
      "R d L′ d′ R′ U l U l′",
      "y2 L d R′ d′ L′ U L F L′",
      "y R U2 R2 U′ F′ U F R2 U′ R′",
      "U2 L U F′ U′ L′ U r U r′",
      "y′ F′ L F L′ U′ L′ U′ L U L′ U L",
      "y2 r B U′ B′ r′ U r U r′",
      "y S′ L′ U′ L U f U F′",
      "y2 z u′ R2 U R U2 R D R′ U R z′ x′",
      "l F U′ F′ R′ F R U l′",
      "y f′ U f R′ U′ R′ U′ R U R′ U R",
      "y′ F R′ F′ r U R U R′ U′ R U′ r′",
      "y2 R′ F′ U F R U′ r′ U′ R U M′",
      "y x′ U′ R U l′ U′ R′ U′ R U R′ U R",
      "y R D r′ U r D′ R′ f R′ f′",
      "R U B′ U′ R′ U l U l′",
      "U2 L d R′ d′ L′ U L F L′",
      "f F′ R U R′ U′ R′ F R f′",
      "y x′ U′ R U R′ x U′ R′ U′ R U R′ U R",
      "U′ F R′ F′ r U R U R′ U′ R U′ r′",
      "r′ U2 R U R2 U L U′ R U x"
    ]
  },
  {
    "id": "OLL -33",
    "category": "T Shapes",
    "preview": "../../previews/oll-33.svg",
    "setup": "F R′ F′ R U R U′ R′",
    "solutions": [
      "R U R′ U′ R′ F R F′",
      "y2 L′ U′ L U L F′ L′ F",
      "F R U′ R′ U R U R′ F′",
      "R U R′ F′ U′ F R U′ R′",
      "y′ r′ U′ r′ D′ r U r′ D r2",
      "y2 F′ L′ U L U′ L′ U′ L F",
      "y2 r′ F′ r U r U′ r′ F",
      "y r U r D r′ U′ r D′ r2",
      "y F U F′ U′ F′ r U r′",
      "M′ U2 M U′ y′ F R F′ R U R′ U′ R′",
      "R′ U′ R U R f′ U′ f"
    ]
  },
  {
    "id": "OLL -34",
    "category": "C Shapes",
    "preview": "../../previews/oll-34.svg",
    "setup": "F U R′ U′ R′ F′ R U R2 U′ R′ y2",
    "solutions": [
      "y2 R U R2 U′ R′ F R U R U′ F′",
      "F R U R′ U′ F′ U F′ r U R′ U′ r′ F R",
      "y f R f′ U′ r′ U′ R U M′",
      "F R U R′ U′ R′ F′ r U R U′ r′",
      "R′ U′ R U F R f′ U′ S",
      "y2 R U R′ U′ R′ F R F′ U R U R′ U R U2 R′",
      "y2 R U2 R2 F R F′ R U′ R′ U′ R′ F R F′",
      "y2 R U R′ U′ R′ F R F′ R′ U2 R U R′ U R",
      "R U2 R′ F R U R′ U′ F′ U R U R′",
      "y2 R′ U2 R2 U R2 U R U2 R′ F R F′",
      "y2 R U R′ U′ M′ U R U′ r′ R U R D R′ U′ R D′ R2",
      "F′ L′ U′ L U L F l′ U′ L′ U l",
      "y′ R2 D′ R U′ R′ D F R F′ U R",
      "y2 R U R′ S R′ F R f′ U R U R′",
      "y R U R′ U2 F2 U′ r′ F r2 U r′ F",
      "y2 F R U R′ d′ x U2 R2 F R F′ R U2 r′",
      "y2 R U R′ U′ B′ R′ F R F′ B",
      "y2 R U R′ U′ y′ r′ U′ R U M′",
      "R U2 R′ U R′ F′ U′ F U R2 U R′",
      "S U S R′ U′ R U R f′ U′ F S′",
      "U2 R U R′ U′ B′ R′ F R F′ B",
      "y2 R U R′ U′ y R′ F′ R M′ U M",
      "y2 R U2 R′ U′ R′ F′ U′ F R2 U′ R2 U2 R",
      "R′ U′ R U y′ l U L′ U′ M′",
      "y′ F U F′ L′ U2 L U′ F′ r U2 R′ U R U2 r′",
      "r U2 R′ U′ R U2 r′ F U L′ U2 L F U′ F′",
      "y2 R U R′ U′ y′ r′ U′ R U R′ r",
      "R′ U′ R M U f R f′ U2 M′",
      "y2 R U R′ M′ U′ F′ U′ F U2 M",
      "y2 R U R′ U′ y R′ F′ r U r′ R",
      "y2 R U R′ U′ f′ U′ F U S",
      "y2 R U R′ U′ x D′ R′ U R E′",
      "x U2 R2 U r′ U′ r B U′ R2 U2 x′",
      "y F′ U′ F U r U R′ U′ M",
      "y R′ U′ F U R U′ S R′ F′ R S′",
      "y2 R U R′ U′ x D′ R′ U R U′ D x′",
      "y2 R U R′ U′ y R′ F′ r U R r′",
      "y2 R′ U2 R U R′ F′ U′ F U R U2 R′ U′ R",
      "U2 R U R′ d′ l′ U′ L U L′ l",
      "y2 L′ U′ L d r U R′ U′ R r′",
      "y2 L′ U′ L U y l U L′ U′ M′",
      "U f R f′ U′ r′ U′ R U M′",
      "y2 R U R′ d′ l′ U′ L U L′ l",
      "y2 R U R′ U′ f′ y U′ L U M",
      "U2 R U R′ U′ M′ U R U′ r′ R U R D R′ U′ R D′ R2",
      "R′ U′ R U F R B′ R′ F′ B",
      "y2 R U R′ d′ l′ U′ L U r′ R",
      "y′ F U F′ U′ R′ F′ r U M",
      "R′ U′ R U y r U R′ U′ r′ R",
      "R′ U′ R y U r U R′ U′ M",
      "y2 R U R′ U′ B′ R′ F R S",
      "y′ F U F′ U′ R′ F′ L F L′ R",
      "y′ f′ L′ f U l U L′ U′ M′",
      "L U L′ U′ y′ R′ F′ L F M",
      "y2 R U R′ U′ y′ r′ U′ R U r R′",
      "F R F′ r U R′ r′ R U R′ U′ r U′ r′"
    ]
  },
  {
    "id": "OLL -35",
    "category": "Fish Shapes",
    "preview": "../../previews/oll-35.svg",
    "setup": "R U2 R′ F R′ F′ R2 U2 R′",
    "solutions": [
      "R U2 R′ R′ F R F′ R U2 R′",
      "f R U R′ U′ f′ R U R′ U R U2 R′",
      "y L′ U2 L2 F′ L′ F L′ U2 L",
      "R′ U2 R U R′ U R U2 F R U R′ U′ F′",
      "y′ R U2 R′ U′ R U′ R′ U2 F R U R′ U′ F′",
      "R U2 R′ d′ R′ F R U′ R′ F′ R",
      "y2 R2 F R F′ R U2 R′ U R U2 R′ U′ R",
      "y2 F R′ F′ R2 U′ R′ U2 R U′ R′ U2 R U R′",
      "R U2 R2 F R F′ R U2 R′",
      "F′ U2 F U r U′ r′ U r U r′",
      "y R2 D r′ U r D′ r′ U′ R′ U M′",
      "y′ R′ U2 R l U′ R′ U l′ U2 R",
      "U′ x′ R′ F2 R2 U′ R′ U R′ F2 R x",
      "R U2 R2 x U R U′ R x′ U2 R′",
      "F′ U2 F2 R′ F′ R F′ U2 F",
      "y′ R′ U2 l R U′ R′ U l′ U2 R"
    ]
  },
  {
    "id": "OLL -36",
    "category": "W Shapes",
    "preview": "../../previews/oll-36.svg",
    "setup": "F′ L F L′ U′ L′ U′ L U L′ U L y2",
    "solutions": [
      "y2 L′ U′ L U′ L′ U L U L F′ L′ F",
      "y2 R U R′ F′ R U R′ U′ R′ F R U′ R′ F R F′",
      "y F U R U′ R′ F′ U′ R U2 R′ U′ R U′ R′",
      "R U B U′ B′ U2 R′ U′ R U′ R′",
      "y R U R2 F′ U′ F U R2 U2 R′",
      "R U R′ U′ F′ U2 F U R U R′",
      "y2 R′ F′ U′ F2 U R U′ R′ F′ R",
      "y F R U R′ U′ R U R′ U′ R′ F′ r U R U′ r′",
      "y2 R′ U′ R U′ R′ U2 R U′ F R U R′ U′ F′",
      "y F R′ F′ R U R U R′ U′ R U R′ U′ R U′ R′",
      "y2 l′ U′ L U′ L′ U L U R U′ r′ F",
      "R U R′ U2 F′ U′ F U′ R U′ R′",
      "F R U R′ U′ F′ U′ r′ U2 R U R′ U r",
      "R U2 r D r′ U2 r D′ r′ R′",
      "R U R′ U R′ F R F′ U′ R U R′ U′ R U′ R′",
      "y2 l′ U′ L U l F′ L′ U′ L′ U L F",
      "y2 R′ U′ R U′ R′ U2 F′ U′ F U R",
      "y′ R U′ R′ U′ F U R U′ R′ F′ R U2 R′",
      "R′ U′ R U′ R′ U R U l U′ R′ U x",
      "R′ U′ R U′ R′ U R U R f′ U′ f",
      "R′ U′ R U′ R′ U R U R B′ R′ B",
      "y2 r U′ r2 D r2 U′ r2 U r2 U D′ r′",
      "L′ U2 L r U2 R′ U′ R U2 r′ F",
      "R′ U′ R U′ R′ U R U l U′ R′ U",
      "U R U R2 F′ U′ F U R2 U2 R′",
      "R′ U′ R U′ R′ U R U R y R′ F′ R",
      "U2 L′ U′ L U′ L′ U L U L F′ L′ F",
      "R′ F′ U2 F R U2 R′ U′ R U2 R′ U2 R",
      "F U2 r U2 r′ F U2 F2 U2 F r U r′",
      "R U2 R2 F2 r U′ R U2 r′ F",
      "R′ U′ R U′ R′ U R U R x′ U′ R′ U x",
      "R U R′ d′ L′ U2 L d R U R′",
      "U2 l′ U′ L U′ L′ U2 l R U R′ L′ U2 R U′ R′ U2 L U R U′ R′ U",
      "U2 R′ F′ r U′ r′ F2 U′ R U R′ U′ R2 D R′ U R D′ R′ U2 R′ U R",
      "U2 R U R′ F′ R U R′ U′ R′ F R U′ R′ F R F′",
      "R′ U′ R U′ R′ U R U x′ R U′ R′ U",
      "y′ R U R′ U′ R′ U′ F R F′ U′ R′ U2 R",
      "R′ U′ R U′ R′ U R U y F R′ F′ R",
      "y2 r′ F′ r U′ r′ F r U r U′ r′ F"
    ]
  },
  {
    "id": "OLL -37",
    "category": "Fish Shapes",
    "preview": "../../previews/oll-37.svg",
    "setup": "F R U′ R′ U R U R′ F′",
    "solutions": [
      "F R U′ R′ U′ R U R′ F′",
      "F R′ F′ R U R U′ R′",
      "R U R′ U′ R′ F R F′ R U R′ U′ R′ F R F′",
      "y F′ r U r′ U′ r′ F r",
      "R′ F′ U F U F′ U′ F R",
      "y2 r2 D′ r U′ r′ D r U r",
      "y′ R U2 R′ F R′ F′ R2 U2 R′",
      "y2 F R U R′ F′ U′ F′ r U r′",
      "M′ U R U′ r′ y U′ L′ U L",
      "y r2 D r′ U r D′ r′ U′ r′",
      "y′ R U R′ F′ U F R U′ R′",
      "R′ F R F′ U′ F′ U F",
      "y F′ L F L′ U′ L′ U L",
      "U′ R U2 R′ F R′ F′ R2 U2 R′",
      "y2 F R U R′ F′ U′ F′ L F L′",
      "U F′ r U r′ U′ r′ F r",
      "y L F′ L′ F U F U′ F′"
    ]
  },
  {
    "id": "OLL -38",
    "category": "Fish Shapes",
    "preview": "../../previews/oll-38.svg",
    "setup": "F R′ F′ R U R U R′ U′ R U′ R′",
    "solutions": [
      "R U R′ U R U′ R′ U′ R′ F R F′",
      "r U R′ U R U′ R′ U′ r′ F R F′",
      "L′ U′ L F L′ U′ L U L F′ L′ U L F′ L′ F",
      "y2 L′ U′ L U F U2 F′ U′ L′ U′ L",
      "r U R′ U′ r′ F R U R U′ R′ F′",
      "y R U R′ F′ R U R′ U′ R′ F R2 U′ R′ F R U R′ U′ F′",
      "y′ R′ U′ R2 B U B′ U′ R2 U2 R",
      "y F R U′ R′ S U′ R U R′ f′",
      "y2 L′ U2 l′ D′ l U2 l′ D l L",
      "l′ U l2 D′ l2 U l2 U′ l2 U′ D l",
      "U2 F R U′ R2 F R F′ U′ F2 r U r2 F2 r",
      "y2 L U L′ U L U′ L′ U′ L′ B L B′",
      "y2 r′ F′ r U F U2 F′ U′ r′ F′ r",
      "y R′ F R2 U R′ U′ R′ F R2 U′ R′ U′ R U R′ F′ R′ F′ R",
      "U′ F R U R′ U′ F′ U′ S R U R′ U′ R′ F R f′",
      "z′ U L U′ L U L′ U′ L′ U′ F U F′",
      "R U R′ U R U′ R′ U′ R′ x U R U′ x′",
      "y2 R U R′ U F′ U F U2 R U′ R′",
      "y2 L U L′ U L U′ L′ U′ y2 R′ F R F′",
      "R′ U2 r′ D′ r U2 r′ D R r"
    ]
  },
  {
    "id": "OLL -39",
    "category": "Fish Shapes",
    "preview": "../../previews/oll-39.svg",
    "setup": "L U F′ U′ L′ U L F L′ y′",
    "solutions": [
      "y L F′ L′ U′ L U F U′ L′",
      "y′ R U R′ F′ U′ F U R U2 R′",
      "y F R U R′ U′ F′ R′ U′ R U′ R′ U2 R",
      "y′ f′ r U r′ U′ r′ F r S",
      "y′ F R U R′ U′ R U R′ U′ R U′ R′ U′ R U R′ F′",
      "y f′ U′ L′ U L f R′ U′ R U′ R′ U2 R",
      "y2 L′ l′ D′ l U′ l′ D l U L",
      "y2 M F R′ F′ R U R U′ R′ U′ M′",
      "y2 f R′ F′ U′ R′ U R S′",
      "y R U2 R′ U′ R U′ R′ F U R U′ R′ F′",
      "y′ F′ L′ U′ L U F U′ R U2 R′ U′ R U′ R′",
      "y′ S′ U′ F R′ F′ R U R U′ R′ S",
      "y R U R′ U′ F2 L F L′ F U′ R U R′",
      "y′ f′ L F L′ U′ L′ U L S",
      "F R′ F′ U′ F U R U′ F′",
      "y′ R B′ R′ U′ R U B U′ R′",
      "r U R′ U R′ F R F′ U2 r′ F R F′",
      "y2 r′ R F R′ F′ R U R U′ R′ U′ M′",
      "y F′ U f R′ U′ R′ U R S′",
      "y′ R U′ r′ U′ F′ U F M′",
      "y r U′ r′ U′ r B U B′ r′",
      "U′ f′ L F L′ U′ L′ U L S",
      "y′ F′ L′ U′ L U F L′ U′ L U′ L′ U2 L",
      "y L F′ L′ U′ L d R d′ L′",
      "U F R U R′ U′ F′ R′ U′ R U′ R′ U2 R",
      "y r U′ r′ z R′ U R F R′ U′",
      "U′ R U R′ F′ U′ F U R U2 R′",
      "y r U′ r′ U′ L U F U′ L′",
      "y′ R U′ r′ y′ U′ R′ U R S′",
      "R′ r′ D′ r U′ r′ D r U R",
      "y2 f R f′ R′ U′ R U f R2 f′",
      "y r U′ r′ U′ r y R U R′ f′",
      "y r U′ r′ U′ r f R f′ r′",
      "y L F′ L′ U′ L U y′ R d′ L′"
    ]
  },
  {
    "id": "OLL -40",
    "category": "Fish Shapes",
    "preview": "../../previews/oll-40.svg",
    "setup": "R′ U′ F U R U′ R′ F′ R y′",
    "solutions": [
      "y R′ F R U R′ U′ F′ U R",
      "y′ F R U R′ U′ F′ R U R′ U R U2 R′",
      "y′ f R′ F′ R U R U′ R′ S′",
      "y′ L′ U′ L F U F′ U′ L′ U2 L",
      "y2 F′ U f z′ r B r′ U′ S′ z",
      "R r D r′ U r D′ r′ U′ R′",
      "r′ R F′ r U r′ U′ r′ F r U M′",
      "y′ f R U′ R′ U′ R U R′ F′ U2 S′",
      "y′ f l′ U′ l U l F′ l′ S′",
      "U F R U R′ F′ R′ F U′ F′ U R",
      "y′ S F R′ F′ R U R U′ R′ S′",
      "y R U R′ U R U′ R′ U′ M′ U2 R U′ R′ U R U2 r′",
      "U R′ F R U R′ U′ F′ U R",
      "U′ R U R′ U′ R′ F R F′ r U R′ U′ r′ F R F′",
      "y R′ F R U R′ U′ y L′ d R",
      "M F′ r U r′ U′ r′ F r U M′"
    ]
  },
  {
    "id": "OLL -41",
    "category": "Awkward Shapes",
    "preview": "../../previews/oll-41.svg",
    "setup": "F U R U′ R′ F′ R U2 R′ U′ R U′ R′ y2",
    "solutions": [
      "y2 R U R′ U R U2 R′ F R U R′ U′ F′",
      "f R U R′ U′ f′ U′ R U R′ U R U2 R′",
      "y2 F U R U′ R′ F′ U R U R′ U R U2 R′",
      "L U L′ U L U2 L′ F′ L′ U′ L U F",
      "R U′ R′ U2 R U B U′ B′ U′ R′",
      "y′ F′ L′ U′ L U F R U R′ U′ M′ U R U′ r′",
      "y′ L F′ L′ F L F′ L′ F L′ U′ L U L′ U′ L y",
      "y2 F U R2 D R′ U′ R D′ R2 F′",
      "y2 R U R′ U R U2 R′ U R′ F′ U′ F U R",
      "y′ S U′ R′ F′ U′ F U R S′",
      "y′ R U R′ U R U′ R′ U R U′ R′ U′ R′ F R F′",
      "y R U2 R′ U′ R U′ R′ U′ F R U R′ U′ F′",
      "y2 M′ R′ F′ U′ F U R U′ M",
      "y2 F R′ F′ R U R U′ R2 U2 R U R′ U R",
      "y′ r U2 R′ U′ R U′ r′ U′ R U R′ U R U2 R′",
      "y2 R′ F′ U′ F R S′ R′ U R S",
      "y R U2 R′ U′ R U′ R2 F′ U′ F U R",
      "y2 F R′ F′ U2 R U R U′ R′ U R′ U R",
      "M U′ F′ L′ U′ L U F M′",
      "y′ S F′ L′ U′ L U F U′ S′",
      "y L U2 l′ U l U′ l′ U′ l U′ L′ U L U2 L′",
      "y2 r′ M2 F′ U′ F U R U′ M",
      "y R U2 R′ U′ R U′ R2 y L′ U′ L U F",
      "R U′ R′ U2 R U f R′ f′ U′ R′",
      "y2 L′ U′ L S′ F R U R′ S F′",
      "U2 R U R′ U R U2 R′ F R U R′ U′ F′",
      "y2 r R2 F′ U′ F U R U′ M",
      "y2 F U2 F′ U′ F U′ F2 L′ U′ L U F",
      "y2 U′ R U2 R′ U′ R U′ R2 y′ R′ U′ R U B",
      "y′ L F′ L′ F L F′ L′ F L′ U′ L U L′ U′ L",
      "R U′ R′ U2 R U y R U′ R′ U′ F′"
    ]
  },
  {
    "id": "OLL -42",
    "category": "Awkward Shapes",
    "preview": "../../previews/oll-42.svg",
    "setup": "F U R U′ R′ F′ R′ U2 R U R′ U R",
    "solutions": [
      "R′ U′ R U′ R′ U2 R F R U R′ U′ F′",
      "y F R U R′ U′ F′ R U R′ U′ M′ U R U′ r′",
      "y2 L′ U′ L U′ L′ U2 L F′ L′ U′ L U F",
      "y R′ F R F′ R′ F R F′ R U R′ U′ R U R′",
      "M U F R U R′ U′ F′ M′",
      "y F R′ F′ R U2 R′ U′ R2 U′ R2 U2 R",
      "R′ U′ R U′ R′ U2 R U R′ F′ U′ F U R",
      "y F S′ R U R′ U′ F′ U S",
      "y2 R′ U R U2 R′ U′ F′ U F U R",
      "f′ L′ U′ L U f U L′ U′ L U′ L′ U2 L",
      "y R′ U′ F2 u′ R U R′ D R2 B",
      "y R′ U′ F′ U F R U′ R U2 R′ U′ R U′ R′",
      "y′ R′ U′ R U′ R′ U R U′ R′ U R U R B′ R′ B",
      "y R′ U2 R U R′ U R U F R U R′ U′ F′",
      "y2 F′ U′ L′ U L F U2 R U2 R′ U′ R U′ R′",
      "y F R′ F′ R U R U′ R′ r′ F′ r U′ r′ F2 r",
      "y′ L′ U2 L U L′ U L U′ F R U R′ U′ F′",
      "y2 F′ U2 F U F′ U F2 R U R′ U′ F′",
      "R′ U′ R U F R U R′ U′ R′ U R U′ F′",
      "y R U R′ U′ M′ U R U′ r′ F R U R′ U′ F′",
      "y R′ F R U R′ F′ R F U′ R U R′ U′ F′",
      "y R′ F2 r U r′ F R2 U2 R′ U′ R U′ R′",
      "y′ R′ U2 r U′ r′ U r U r′ U R U′ R′ U2 R",
      "y S′ U L F U F′ U′ L′ S",
      "R B U B′ R′ S′ R U′ R′ S",
      "y′ R′ U R U′ R2 F′ U′ F U R U′ R U′ R′ U R",
      "y F R f′ R′ F′ U′ F R U′ S",
      "y2 F′ U′ L2 D′ L U L′ D L2 F",
      "y′ x′ L′ U L U′ L′ U L U′ x L U L′ U′ L U L′ U",
      "R′ F2 R2 U′ F U′ F′ U2 R2 F2 R",
      "y x R′ U R U′ R′ U R U′ x′ R U R′ U′ R U R′",
      "B′ U′ R2 D′ R U R′ D R2 B",
      "r′ R2 B U B′ U′ R′ U M′",
      "y f′ F2 R U R′ U′ F′ U S",
      "y r′ U′ M′ F R′ F′ R2 r′ U r",
      "U F R′ F′ R U2 R′ U′ R2 U′ R2 U2 R",
      "y L′ U′ L U′ L′ U L U′ L′ U L U L F′ L′ F",
      "y r′ U′ r R′ F R′ F′ R2 r′ U r",
      "y f R f′ M′ R′ F′ U′ F M R",
      "y2 R U R′ S F′ L′ U′ L S′ F",
      "M R B U B′ U′ R′ U M′",
      "y R′ U′ F2 u′ R U R′ u F2 R",
      "R′ U′ R U′ R′ U2 R B′ R′ U′ R U B",
      "y R′ U2 R U R′ U R2 B U B′ U′ R′",
      "y R′ U2 R U R′ U R2 y R U R′ U′ F′",
      "L′ U L U2 L′ U′ y′ L′ U L U F"
    ]
  },
  {
    "id": "OLL -43",
    "category": "P Shapes",
    "preview": "../../previews/oll-43.svg",
    "setup": "f′ U′ L′ U L f",
    "solutions": [
      "y R′ U′ F′ U F R",
      "y F U R U′ R′ F′ R U2 R′ U′ R U′ R′",
      "y2 R′ U′ F R′ F′ R U R",
      "y′ R U R′ F′ L′ U′ L F",
      "y′ R U R′ F′ U2 F R U′ R′",
      "r′ U′ R′ F R F′ U r",
      "y R U′ R′ U′ F′ U2 F U R U′ R′",
      "y2 F′ U′ L′ U L F",
      "f′ L′ U′ L U f",
      "y′ r′ F′ U′ F U r",
      "B′ U′ R′ U R B",
      "U R′ U′ F′ U F R",
      "y2 b′ R′ U′ R U b",
      "y′ L′ d′ R′ U R B",
      "y2 z F′ R′ U′ R U F z′",
      "U2 F′ U′ L′ U L F",
      "y2 F′ U′ r′ F r F",
      "y2 R2 F R F′ R U2 R′ F′ U2 F R"
    ]
  },
  {
    "id": "OLL -44",
    "category": "P Shapes",
    "preview": "../../previews/oll-44.svg",
    "setup": "f U R U′ R′ f′",
    "solutions": [
      "f R U R′ U′ f′",
      "R U B′ R B R′ U′ R′",
      "y′ F R U′ R′ U2 R U R′ F′",
      "y′ F R U′ R′ F′ L′ U L",
      "R U2 R2 F R F′ U′ R U′ R′",
      "f R2 D R′ U R D′ R2 U′ f′",
      "y2 r U x′ R U′ R′ U x U′ r′",
      "y2 F U R U′ R′ F′",
      "y R U B U′ B′ R′",
      "y′ L U F U′ F′ L′",
      "y2 x U′ L U2 R′ U′ M U′ L′ U L U2 R U2 R′",
      "y2 z′ F L U L′ U′ b′",
      "B L′ B′ L U B′ U F U R′ U′ R F′ B",
      "B L′ B′ L U B′ U′ B L F U′ F′ L′ U′",
      "B′ U R B′ R′ B U F U R′ U′ R F′ B",
      "B′ U R B′ R′ B U′ B L F U′ F′ L′ U′",
      "B′ R′ B L′ B′ R U B U B′ U′ B L U",
      "B′ R′ B L′ B′ R U B U′ L F U′ F′ U′",
      "B′ D B U R U B U′ B′ R′ B′ D′ B U",
      "B′ D B2 U L U′ L′ B′ U B′ D′ B U",
      "B′ D′ B U R U B U′ B′ R′ B′ D B U",
      "B′ D′ B2 U L U′ L′ B′ U B′ D B U",
      "U2 F U R U′ R′ F′",
      "y2 R B R′ U2 R U R′ U R U′ B′ U′ R′"
    ]
  },
  {
    "id": "OLL -45",
    "category": "T Shapes",
    "preview": "../../previews/oll-45.svg",
    "setup": "F U R U′ R′ F′",
    "solutions": [
      "F R U R′ U′ F′",
      "y R′ F′ U′ F U R",
      "F R2 D R′ U R D′ R2 U′ F′",
      "y2 f U R U′ R′ f′",
      "y2 F′ L′ U′ L U F",
      "f′ U′ L′ U L f",
      "y′ r′ U′ F′ U F r",
      "y′ R B U B′ U′ R′",
      "U2 F′ L′ U′ L U F",
      "y2 B L U L′ U′ B′"
    ]
  },
  {
    "id": "OLL -46",
    "category": "C Shapes",
    "preview": "../../previews/oll-46.svg",
    "setup": "R′ U′ F R′ F′ R U R",
    "solutions": [
      "R′ U′ R′ F R F′ U R",
      "y F R U R′ U′ F′ U′ R U R′ U R U2 R′",
      "y′ F R U R′ U′ F′ U R′ U′ R U′ R′ U2 R",
      "y′ F R U R′ U′ F′ U2 R U2 R′ U′ R U′ R′",
      "y F R U R′ y′ R′ U R U2 R′",
      "y2 L U L F′ L′ F U′ L′",
      "R′ F′ U′ F R U′ R′ U2 R",
      "y2 f R U R′ U′ f′ r U R′ U′ r′ R U R U′ R′",
      "y2 r′ U′ F R′ F′ R U r",
      "l′ U2 L2 F′ L′ F U L′ U l",
      "R′ F′ U′ R U R′ U′ R′ F R2 U′ R′ U R",
      "R′ U′ l′ U R U′ x′ U R",
      "y′ F R U R2 U′ R F′ U′ R′ U2 R",
      "y2 L F U′ R U R′ F′ L′",
      "y2 r′ F′ r′ F r U′ F r",
      "y′ R U R2 U′ R′ F R2 F′ R′ U R",
      "y′ x′ U′ R′ F′ R U F′ U′ F2 U x",
      "y2 r U2 R2 F R F′ U′ R U′ r′",
      "R U R B′ R′ B U′ R′",
      "y F U F R′ F′ R U′ F′",
      "R U x′ R U′ R′ U x U′ R′",
      "R2 D r′ U′ r D′ R2 F′ U F",
      "y2 r′ F′ L′ U L U′ F r",
      "y F R U R′ F′ d R U2 R′"
    ]
  },
  {
    "id": "OLL -47",
    "category": "L Shapes",
    "preview": "../../previews/oll-47.svg",
    "setup": "F′ U′ L′ U L U′ L′ U L F",
    "solutions": [
      "F′ L′ U′ L U L′ U′ L U F",
      "y′ F U R U′ R′ F′ R U R′ U R U2 R′",
      "R′ U′ R′ F R F′ R′ F R F′ U R",
      "y′ F R′ F′ R U2 R U′ R′ U R U2 R′",
      "R′ F′ r U′ r′ F2 R2 U2 R′ U′ R U′ R′",
      "y2 f′ U f U2 R′ U′ R U′ R2 U2 R",
      "y′ R′ F′ U′ F U F′ U′ F U R",
      "y2 f′ U′ L′ U L U′ L′ U L f",
      "F′ r′ F′ r U r′ F′ r U F",
      "b′ U′ R′ U R U′ R′ U R b",
      "y2 B′ R′ U′ R U R′ U′ R U B",
      "z F′ U′ R′ U R U′ R′ U R F z′",
      "U′ F R′ F′ R U2 R U′ R′ U R U2 R′",
      "y2 R U R2 F R F′ U f R′ F′ R S′",
      "y2 R B′ R B R2 U2 f R′ F′ R S′",
      "y2 S′ R U2 R2 U′ R2 U′ R2 U2 R S",
      "y f′ U f U2 R′ U2 R′ U2 F R F′",
      "z F′ U′ R′ U R U′ R′ U R F",
      "y′ x U R′ U′ R x′ U2 R U′ R′ U R U2 R′",
      "R′ U′ x R′ U R U′ R′ U R U′ x′ U R",
      "y′ R′ z x U′ R′ U R U′ R′ U R F",
      "R′ U′ l′ U R U′ R′ U R U′ x′ U R"
    ]
  },
  {
    "id": "OLL -48",
    "category": "L Shapes",
    "preview": "../../previews/oll-48.svg",
    "setup": "F U R U′ R′ U R U′ R′ F′",
    "solutions": [
      "F R U R′ U′ R U R′ U′ F′",
      "r U2 R′ U′ R U R′ U2 r′ F R F′",
      "R′ U′ F′ U F R2 U2 R′ U′ R U′ R′",
      "R U2 R′ U′ R U R′ U2 R′ F R F′",
      "y F′ r U r′ U2 r′ F r U′ r′ F2 r",
      "F R′ F′ U2 R U R′ U R2 U2 R′",
      "y2 R U R′ U R U2 R′ U′ F R U R′ U′ F′",
      "y2 f U R U′ R′ U R U′ R′ f′",
      "y2 B L U L′ U′ L U L′ U′ B′",
      "y2 R U R′ U R U2 R2 F′ U′ F U R",
      "y′ f U′ f′ U2 x′ r U2 r B2 U′ r′ F",
      "z′ F U L U′ L′ U L U′ L′ b′",
      "y′ R B U B′ U′ B U B′ U′ R′"
    ]
  },
  {
    "id": "OLL -49",
    "category": "L Shapes",
    "preview": "../../previews/oll-49.svg",
    "setup": "r′ U r2 U′ r2 U′ r2 U r′ y2",
    "solutions": [
      "y2 r U′ r2 U r2 U r2 U′ r",
      "y F U R U′ R′ F′ R′ U′ R U′ R′ U2 R",
      "y F U R U′ R′ F′ U R U2 R′ U′ R U′ R′",
      "y′ R′ U2 R U R′ U R F R U R′ U′ F′",
      "y2 r U2 R2 U′ R2 U′ r′ R′ U2 R",
      "y L′ U2 L U L′ U L F′ L′ U′ L U F",
      "y2 R′ F R′ F′ R2 U2 B′ R B R′",
      "y F R′ F2 R U2 R U2 R′ F",
      "y F L′ U2 L U2 L F2 L′ F",
      "y2 r U R′ U R U2 r′ l′ U2 L U L′ U l",
      "y2 r U2 R2 U′ R2 U′ R2 U2 R U2 M",
      "y2 r U2 R2 U′ R2 U′ r2 U2 R U2 M′",
      "l U′ l2 U l2 U l2 U′ l",
      "R B′ R2 F R2 B R2 F′ R",
      "y2 S R U2 R2 U′ R2 U′ R2 U2 R U S′",
      "R f′ U2 F U2 f R2 F′ R",
      "U F R′ F2 R U2 R U2 R′ F",
      "y r′ U′ R U′ R′ U2 r2 U2 R′ U′ R U′ r′",
      "U2 r U′ r2 U r2 U r2 U′ r",
      "y2 L F′ L2 B L2 F L2 B′ L",
      "y2 R′ F R′ F′ R2 d2 y′ R′ F R F′",
      "y′ F′ L F′ L′ F2 U2 R′ F R F′"
    ]
  },
  {
    "id": "OLL -50",
    "category": "L Shapes",
    "preview": "../../previews/oll-50.svg",
    "setup": "r U′ r2 U r2 U r2 U′ r",
    "solutions": [
      "r′ U r2 U′ r2 U′ r2 U r′",
      "y′ R U2 R′ U′ R U′ R′ F R U R′ U′ F′",
      "y′ F′ U′ L′ U L F L U L′ U L U2 L′",
      "y′ F′ R U2 R′ U2 R′ F2 R F′",
      "y′ F R U′ R′ U′ R U R′ U R U′ R′ F′",
      "y2 L F′ L F L2 d2 y L F′ L′ F",
      "y2 l′ U′ L U′ L′ U2 l r U2 R′ U′ R U′ r′",
      "y2 R′ U R U′ R2 F R2 U R′ U′ F′ R",
      "y2 l′ U2 L2 U L2 U l L U2 L′",
      "y r U R′ U R U2 r2 U2 R U R′ U r",
      "L U′ y′ R′ U2 R′ U R U′ R U2 R d′ L′",
      "y2 R′ F R2 B′ R2 F′ R2 B R′",
      "y2 l′ U l2 U′ l2 U′ l2 U l′",
      "U R′ U2 R U R′ U R f R U R′ U′ f′",
      "U′ R U2 R′ U′ R U′ R′ F R U R′ U′ F′",
      "L′ f U2 F′ U2 f′ L2 F L′",
      "R B′ R B R2 U2 F R′ F′ R",
      "y F R′ F R F2 U2 L F′ L′ F"
    ]
  },
  {
    "id": "OLL -51",
    "category": "L Shapes",
    "preview": "../../previews/oll-51.svg",
    "setup": "f U R U′ R′ U R U′ R′ f′",
    "solutions": [
      "f R U R′ U′ R U R′ U′ f′",
      "y2 F R U R′ U′ R U R′ U′ R U R′ U′ R U R′ U′ F′",
      "y r′ F′ U′ F U F′ U′ F U r",
      "y′ R′ U′ R′ F R F′ R U′ R′ U2 R",
      "R U2 R′ U2 R′ F R2 U R′ U′ F′",
      "y R′ U2 R U R′ F R′ F′ R U R",
      "y2 F U R U′ R′ U R U′ R′ F′",
      "U′ R′ U′ R′ F R F′ R U′ R′ U2 R",
      "y′ R′ U′ F′ U F U′ F′ U F R",
      "y′ R U R′ U′ R U R′ U′ R′ F R2 U′ R′ U′ R U R′ F′ R U R′ U R′ F R F′",
      "y′ L U L F′ L′ F L′ U L U2 L′",
      "U2 F U R U′ R′ U R U′ R′ F′ U2",
      "U2 F U R U′ R′ U R U′ R′ F′",
      "F′ U′ L′ U L U′ L′ U L F",
      "y2 f′ L′ U′ L U L′ U′ L U f"
    ]
  },
  {
    "id": "OLL -52",
    "category": "L Shapes",
    "preview": "../../previews/oll-52.svg",
    "setup": "F R U R′ d R′ U′ R U′ R′",
    "solutions": [
      "y2 R′ F′ U′ F U′ R U R′ U R",
      "y F R U R′ U′ F′ U2 R U R′ U R U2 R′",
      "R′ U′ R U′ R′ U y′ R′ U R B",
      "y F R U R′ U′ F′ L U L′ U L U2 L′",
      "R U R′ U R U′ B U′ B′ R′",
      "y′ F R U R′ y′ U R′ U′ R U′ R′",
      "y2 R′ U′ F R′ F′ R F R′ F′ R U R",
      "R′ U′ R U′ R′ U2 R U′ f′ L′ U′ L U f",
      "R U R′ U R U2 R′ U′ f R U R′ U′ f′",
      "y′ F U R U′ R2 F′ R U2 R U2 R′",
      "y′ F U R U′ R′ F′ r U R′ U R U2 r′",
      "y r U2 R′ U′ R U′ r′ F R U R′ U′ F′",
      "R′ U′ F′ U F′ L F L′ F R",
      "r′ U′ R′ F R F′ R′ F R F′ U r",
      "y′ F U l′ U R U′ R′ U l F′ U′ F′",
      "y R U′ R′ F′ U′ F U2 R U R′ U′ R U R′",
      "y2 R U2 R2 U′ R U′ R′ U2 r U R U′ r′",
      "R U R′ U R d′ R U′ R′ F′",
      "R U R′ U R U′ y R U′ R′ F′",
      "R′ U′ R U′ R′ U F′ U F R",
      "R U R′ U R U′ f R′ f′ R′",
      "U F U R U2 R′ U2 R U2 R′ U′ F′",
      "y′ R′ F R F′ U2 R U R′ U′ R′ F R F′ R U′ R′",
      "y2 R U2 R2 u′ R U′ R′ U R′ u R",
      "R U R′ U′ M′ U R U′ r′ U′ r U r′ U2 r U2 R′ U2 R U′ r′",
      "y2 L U L′ U L U′ F U′ F′ L′",
      "U′ F R′ F′ r U M U R U′ R′ U R U′ M′ U′ r′",
      "y2 L U L′ U L U′ y′ z′ U L′ U′ b′",
      "y2 R f R f′ U R′ U′ R U′ R′",
      "R U R′ U R y U′ R U′ R′ F′",
      "x′ R F R′ F R F′ U F′ U′ R′ x",
      "R U R′ U R U′ x′ U F′ U′ R′ x",
      "U2 R′ F′ U′ F U′ R U R′ U R",
      "R′ U′ y L′ U L′ y′ L F L′ F R",
      "y2 L′ U′ L U′ L′ U B′ U B L",
      "R′ U′ R U′ R′ d R′ U R B"
    ]
  },
  {
    "id": "OLL -53",
    "category": "Lightning Shapes",
    "preview": "../../previews/oll-53.svg",
    "setup": "r′ U2 R U R′ U′ R U R′ U r",
    "solutions": [
      "y r′ U2 R U R′ U′ R U R′ U r",
      "f R U R′ U′ f′ L F R′ F′ L′ F R F′",
      "r′ U′ R U′ R′ U R U′ R′ U2 r",
      "y2 F R U R′ U′ F′ R U R′ U′ R′ F R F′",
      "y′ l′ U′ l L′ U′ L U L′ U′ L U l′ U l",
      "y2 F R U R′ U′ R U′ R′ U R U R′ F′",
      "y′ R′ F R F′ U2 R2 B′ R′ B R′",
      "y′ R′ F R F′ U′ F R′ F′ R2 U′ R′",
      "y2 l′ U′ L U′ L′ U L U′ L′ U2 l",
      "y′ l′ U2 L U L′ U′ L U L′ U l",
      "y2 R′ F′ r U′ r′ F r U′ r′ F2 R",
      "f R U R′ U′ f′ r U R′ U′ L′ U l F′",
      "x′ D′ L2 U L U′ L′ U L U′ L D x",
      "U2 l′ U′ L U′ L′ U L U′ L′ U2 l",
      "y r U′ r′ U′ r U r′ U r U R′ U′ M",
      "U2 F R U R′ U′ F′ R U R′ U′ R′ F R F′",
      "F′ L F L′ U2 F2 R′ F′ R F′",
      "y′ R′ F R F′ U2 R2 y R′ F′ R F′",
      "y r′ U′ r R′ U′ R U R′ U′ R U r′ U r",
      "y′ R′ F R F′ U2 l R U′ R′ U l′",
      "y′ R′ F2 r U r′ F′ r U r′ F R",
      "y2 R′ F′ r U′ L′ U L U′ r′ F2 R",
      "U r′ U2 R U R′ U′ R U R′ U r"
    ]
  },
  {
    "id": "OLL -54",
    "category": "Lightning Shapes",
    "preview": "../../previews/oll-54.svg",
    "setup": "r U2 R′ U′ R U R′ U′ R U′ r′",
    "solutions": [
      "y′ r U2 R′ U′ R U R′ U′ R U′ r′",
      "y f R U R′ U′ f′ R U2 R2 U′ R2 U′ R2 U2 R",
      "r U R′ U R U′ R′ U R U2 r′",
      "y′ r U r′ R U R′ U′ R U R′ U′ r U′ r′",
      "y′ F U R U′ R′ U R U′ R′ S U R U′ R′ f′",
      "F′ L′ U′ L U F U2 R U R′ U′ R′ F R F′",
      "F′ L′ U′ L U F L′ U′ L U L F′ L′ F",
      "y2 f′ L′ U′ L U f U2 L F R′ F′ L′ F R F′",
      "y r′ U2 R U R′ U r R′ U2 R U R′ U R",
      "F′ L′ U′ L U L′ U L U′ L′ U′ L F",
      "y R B′ R′ B U2 R2 F R F′ R",
      "y2 x′ D R2 U′ R′ U R U′ R′ U R′ D′ x",
      "y2 l U L′ U L U′ L′ U L U2 l′",
      "y′ x U′ L U2 R′ U′ M U′ L′ U L U R U R′ U′ R U′ R′",
      "y l U2 L′ U′ L U L′ U′ L U′ l′",
      "y l U l′ L U L′ U′ L U L′ U′ l U′ l′",
      "y2 M R U R′ U R U′ R′ U R U2 R′ U′ M′",
      "U′ r U2 R′ U′ R U R′ U′ R U′ r′",
      "y2 F R′ F′ R U2 F2 L F L′ F",
      "y′ L F′ L′ F U2 L2 y′ L F L′ F",
      "y′ r U′ r′ F U2 r2 F r U′ r"
    ]
  },
  {
    "id": "OLL -55",
    "category": "Line Shapes",
    "preview": "../../previews/oll-55.svg",
    "setup": "F R′ F′ U2 R U R′ U R2 U2 R′",
    "solutions": [
      "y F R U R′ U′ F′ R U2 R2 U′ R2 U′ R2 U2 R",
      "y R′ F R U R U′ R2 F′ R2 U′ R′ U R U R′",
      "y′ r U2 R′ U′ r′ R2 U R′ U′ r U′ r′",
      "y r U2 R′ U′ M R U R′ U′ r U′ r′",
      "R U2 R2 U′ R U′ R′ U2 F R F′",
      "y F R U R′ U′ S R U R′ U′ S′ R U R′ U′ F′",
      "y R′ F U R U′ R2 F′ R2 U R′ U′ R",
      "r U2 R2 F R F′ U2 r′ F R F′",
      "y F U′ R2 D R′ U2 R D′ R2 U F′",
      "y R U2 R′ U′ R U′ R′ U′ r′ U′ R U′ R′ U2 r",
      "L′ U2 L2 U L′ U L U2 F′ L′ F",
      "R′ U2 R2 U R′ U R U2 y R′ F′ R",
      "R′ U′ F R′ F′ R F U R U′ R′ F′ R",
      "y R U R′ U R U′ R′ F′ R U R′ U′ R′ F R U′ R′ F R F′",
      "y B′ U x R2 F′ R B2 R′ F R2 x′ U′ B",
      "R′ U F2 D′ F U2 F′ D F2 U′ R",
      "y F R′ F′ R U R U′ R2 F2 r U r′ F R",
      "R′ U′ F U R U′ R B′ R2 F′ R2 B R′",
      "R′ d R2 D′ R U2 R′ D R2 U′ B",
      "y R U′ r′ U′ R U′ R′ U r U R′ U′ M U M′",
      "U r U2 R′ U′ r′ R2 U R′ U′ r U′ r′",
      "y r U′ r′ U′ r U r′ R U R′ r U′ r′ U r U r′",
      "U R′ F U R U′ R2 F′ R2 U R′ U′ R",
      "U R′ F R U R U′ R2 F′ R2 U′ R′ U R U R′",
      "U′ R′ F U R U′ R2 F′ R2 U R′ U′ R",
      "R U′ y R2 D R′ U2 R D′ R2 U F′",
      "y r U2 R′ U′ r′ R2 U R′ U′ r U′ r′",
      "R U′ y R2 D R′ U2 R D′ R2 d R′",
      "y M U2 r U′ r′ U′ r U′ r′ U r U R′",
      "y r U2 R′ U′ R2 r′ U R′ U′ r U′ r′"
    ]
  },
  {
    "id": "OLL -56",
    "category": "Line Shapes",
    "preview": "../../previews/oll-56.svg",
    "setup": "r U r′ R U R′ U′ R U R′ U′ r U′ r′",
    "solutions": [
      "F R U R′ U′ F′ r U R′ U′ r′ F R F′",
      "r U r′ U R U′ R′ U R U′ R′ r U′ r′",
      "R′ F′ R U′ L′ U L U′ L′ U L R′ F R",
      "r′ U′ r U′ R′ U R U′ R′ U R r′ U r",
      "F R U R′ U′ R F′ r U R′ U′ r′",
      "r U r′ U R U′ R′ M′ U R U2 r′",
      "f R U R′ U′ F′ R U R′ U′ R′ F R f′",
      "y F R U R′ U′ R U R′ U′ S R U R′ U′ f′",
      "R′ F′ R U′ r′ F r M′ U′ r′ F2 R",
      "y f R U R′ U′ f′ F R U R′ U′ R U R′ U′ F′",
      "r U R′ U R U r′ U′ r U r′ F′ U F",
      "R B L B′ R2 f R U′ R′ f′ R",
      "y R U′ R′ U′ S′ R U′ R′ S U R U R′",
      "r U r′ U R U′ R′ U R U′ M′ U′ r′",
      "L′ U2 R U′ r B R′ U2 R′ U′ R U′ x′",
      "F R U R′ U′ F′ L F R′ F′ L′ F R F′",
      "R′ F′ R U′ r′ F r U′ r′ F M′ F R",
      "l′ U′ l U′ L′ U L U′ L′ U L l′ U l",
      "y f R U R′ U′ S′ R U R′ U′ R U R′ U′ F′",
      "U R U R′ U R′ U′ F′ U F R U R U2 R′",
      "y R S U′ R′ U′ R U′ R′ U R U S′ R′",
      "y R U′ R′ M′ U′ R U′ R′ U r′ R2 U R′",
      "l′ U′ l U′ L′ U L M′ U′ L′ U2 l",
      "L′ B′ L U′ R′ U R U′ R′ U R L′ B L"
    ]
  },
  {
    "id": "OLL -57",
    "category": "All Corner Oriented",
    "preview": "../../previews/oll-57.svg",
    "setup": "r U R′ U′ M U R U′ R′",
    "solutions": [
      "R U R′ U′ M′ U R U′ r′",
      "M′ U M′ U M′ U2 M U M U M",
      "r′ F′ r U M′ U′ r′ F R",
      "y S R′ F R S′ R′ F′ R",
      "R′ U′ R U M U′ R′ U r",
      "y R U R′ S′ R U′ R′ S",
      "L′ R U R′ U′ L R′ F R F′",
      "y R U′ R′ S′ R U R′ S",
      "M′ U′ M′ U′ M′ U′ M′ U2 M′ U′ M′ U′ M′ U′ M′",
      "y R U R′ U′ M U R U′ R′ U′ M′",
      "M′ U M U′ M′ U M U M′ U2 M",
      "M′ U′ M U M′ U′ M U′ M′ U2 M",
      "R U R′ S R U′ R′ U S′",
      "R U R′ U′ R′ r U R U′ r′",
      "R U R′ U′ r R′ U R U′ r′",
      "L′ U′ L U M′ U′ L′ U l",
      "M′ U′ M′ U′ M′ U2 M U′ M U′ M U2",
      "R U R′ U′ R′ L F R F′ r′",
      "y M′ U M′ U M′ U M2 U M′ U M′ U M′",
      "l F l′ U′ M′ U R U′ r′",
      "y F′ r′ U′ r F r2 D′ r U r′ D r2",
      "R L′ U R′ U′ L R′ F R F′",
      "y M′ U′ M U′ M′ U′ M U M′ U M",
      "F R U′ R′ U R U R2 F′ r U R U′ r′",
      "L′ U′ L U l′ L U′ L′ U l",
      "y M′ U′ M′ U′ M′ U′ M2 U′ M′ U′ M′ U′ M′ U′",
      "M′ U′ M′ U′ M′ U′ M′ U′ M U M U M U M U",
      "R U′ R′ F′ U F R U R2 F R F′",
      "y M′ U M′ U M′ U M′ U M′ U′ M′ U′ M′ U′ M′ U′",
      "M F R′ F′ M′ F R F′"
    ]
  }
];
